// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package builtins

type STRING_32 struct {
	Len  uint8
	Data [32]byte
}

func (s *STRING_32) SetString(v string) {
	if s == nil {
		return
	}
	n := len(v)
	if n > 32 {
		n = 32
	}
	copy(s.Data[:], v)
	for i := n; i < 32; i++ {
		s.Data[i] = 0
	}
	s.Len = uint8(n)
}

func (s STRING_32) String() string {
	if s.Len == 0 {
		return ""
	}
	return string(s.Data[:s.Len])
}

type STRING_128 struct {
	Len  uint8
	Data [128]byte
}

func (s *STRING_128) SetString(v string) {
	if s == nil {
		return
	}
	n := len(v)
	if n > 128 {
		n = 128
	}
	copy(s.Data[:], v)
	for i := n; i < 128; i++ {
		s.Data[i] = 0
	}
	s.Len = uint8(n)
}

func (s STRING_128) String() string {
	if s.Len == 0 {
		return ""
	}
	return string(s.Data[:s.Len])
}
