// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"testing"
)

func TestRunnerStep_DoesNotPanic(t *testing.T) {
	var r Runner
	// Ensure entrypoint is linked.
	_ = OB_OB1
	defer func() {
		if v := recover(); v != nil {
			t.Fatalf("panic in Runner.Step: %v", v)
		}
	}()
	r.Step()
}
