// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

// TIME represents PLC TIME as nanoseconds.
// It is intentionally compatible with time.Duration (but we avoid importing time in hot paths).
type TIME int64

type Clock interface {
	Now() TIME
}

// TestClock is a deterministic clock for tests.
type TestClock struct {
	now TIME
}

func (c *TestClock) Now() TIME {
	if c == nil {
		return 0
	}
	return c.now
}

func (c *TestClock) Advance(dt TIME) {
	if c == nil {
		return
	}
	c.now += dt
}
