// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"fmt"
	"reflect"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

type debugStepMode uint32

const (
	debugStepModeNone debugStepMode = iota
	debugStepModeInto
	debugStepModeNext
	debugStepModeOut
)

type debugPauseState struct {
	ID     string
	Reason string
	Depth  int
}

const debugMaxStackFrames = 32

type StackFrame struct {
	BlockName  string
	SourceFile string
	SourceLine int
}

type DebugSnapshotVariable struct {
	Name  string
	Value any
	Type  string
}

type debugRuntime struct {
	breakpointsMu     sync.RWMutex
	breakpoints       map[string]struct{}
	active            atomic.Bool
	closed            atomic.Bool
	breakpointsActive atomic.Bool
	pauseRequested    atomic.Bool
	stopOnEntry       atomic.Bool
	stepMode          atomic.Uint32
	stepDepth         atomic.Int32
	stackDepth        atomic.Int32

	pauseMu       sync.Mutex
	pauseState    debugPauseState
	paused        bool
	pausedCh      chan struct{}
	hooksMu       sync.RWMutex
	onPauseWait   func()
	onPauseResume func()
	resumeCh      chan struct{}
	resumeSkip    debugPauseState
	hasResumeSkip bool
	closeCh       chan struct{}
	closeOnce     sync.Once

	stackMu sync.RWMutex
	stack   []StackFrame
}

var debugSnapshotSinkMu sync.RWMutex
var debugSnapshotSink func(string, []DebugSnapshotVariable)

func newDebugRuntime(stopOnEntry bool) *debugRuntime {
	d := &debugRuntime{
		breakpoints: map[string]struct{}{},
		pausedCh:    make(chan struct{}),
		closeCh:     make(chan struct{}),
	}
	d.stopOnEntry.Store(stopOnEntry)
	d.refreshActive()
	return d
}

func normalizeDebugID(id string) string {
	return strings.TrimSpace(id)
}

func (d *debugRuntime) refreshActive() {
	active := !d.closed.Load() && (d.pauseRequested.Load() || d.stopOnEntry.Load() || d.breakpointsActive.Load() || d.stepMode.Load() != uint32(debugStepModeNone))
	d.active.Store(active)
}

func (d *debugRuntime) Enabled() bool {
	if d == nil {
		return false
	}
	return d.active.Load()
}

func SetDebugSnapshotSink(sink func(string, []DebugSnapshotVariable)) {
	debugSnapshotSinkMu.Lock()
	debugSnapshotSink = sink
	debugSnapshotSinkMu.Unlock()
}

func emitDebugSnapshot(id string, vars []DebugSnapshotVariable) {
	if len(vars) == 0 {
		return
	}
	debugSnapshotSinkMu.RLock()
	sink := debugSnapshotSink
	debugSnapshotSinkMu.RUnlock()
	if sink == nil {
		return
	}
	copied := make([]DebugSnapshotVariable, len(vars))
	copy(copied, vars)
	sink(id, copied)
}

func debugSnapshotValue(v any) any {
	return normalizeDebugSnapshotValue(reflect.ValueOf(v))
}

func normalizeDebugSnapshotValue(v reflect.Value) any {
	if !v.IsValid() {
		return ""
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return ""
		}
		v = v.Elem()
	}
	if v.CanInterface() {
		switch val := v.Interface().(type) {
		case bool, int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64, uintptr, float32, float64, string:
			return val
		}
	}
	switch v.Kind() {
	case reflect.Bool:
		return v.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int()
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return v.Uint()
	case reflect.Float32, reflect.Float64:
		return v.Float()
	case reflect.String:
		return v.String()
	default:
		if v.CanInterface() {
			return fmt.Sprintf("%v", v.Interface())
		}
		return ""
	}
}

func (d *debugRuntime) Closed() bool {
	if d == nil {
		return true
	}
	return d.closed.Load()
}

func (d *debugRuntime) IsPaused() bool {
	if d == nil {
		return false
	}
	d.pauseMu.Lock()
	defer d.pauseMu.Unlock()
	return d.paused
}

func (d *debugRuntime) PauseState() debugPauseState {
	if d == nil {
		return debugPauseState{}
	}
	d.pauseMu.Lock()
	defer d.pauseMu.Unlock()
	return d.pauseState
}

func DebugEnabled() bool {
	return defaultDebugRuntime.Enabled()
}

type DebugPauseState = debugPauseState

func DebugIsPaused() bool {
	return defaultDebugRuntime.IsPaused()
}

func CurrentDebugPauseState() DebugPauseState {
	return defaultDebugRuntime.PauseState()
}

func DebugWaitPaused(timeout time.Duration) (DebugPauseState, bool) {
	return defaultDebugRuntime.WaitPaused(timeout)
}

func SetDebugPauseHooks(onWait func(), onResume func()) {
	defaultDebugRuntime.SetPauseHooks(onWait, onResume)
}

func (d *debugRuntime) pausedSignal() chan struct{} {
	if d == nil {
		ch := make(chan struct{})
		close(ch)
		return ch
	}
	d.pauseMu.Lock()
	ch := d.pausedCh
	d.pauseMu.Unlock()
	return ch
}

func (d *debugRuntime) WaitPaused(timeout time.Duration) (debugPauseState, bool) {
	if d == nil {
		return debugPauseState{}, false
	}
	pausedCh := d.pausedSignal()
	if timeout <= 0 {
		select {
		case <-pausedCh:
			return d.PauseState(), true
		case <-d.closeCh:
			if d.IsPaused() {
				return d.PauseState(), true
			}
			return debugPauseState{}, false
		}
	}
	timer := time.NewTimer(timeout)
	defer timer.Stop()
	select {
	case <-pausedCh:
		return d.PauseState(), true
	case <-d.closeCh:
		if d.IsPaused() {
			return d.PauseState(), true
		}
		return debugPauseState{}, false
	case <-timer.C:
		return debugPauseState{}, false
	}
}

func (d *debugRuntime) SetPauseHooks(onWait func(), onResume func()) {
	if d == nil {
		return
	}
	d.hooksMu.Lock()
	d.onPauseWait = onWait
	d.onPauseResume = onResume
	d.hooksMu.Unlock()
}

func (d *debugRuntime) pauseHooks() (func(), func()) {
	if d == nil {
		return nil, nil
	}
	d.hooksMu.RLock()
	defer d.hooksMu.RUnlock()
	return d.onPauseWait, d.onPauseResume
}

func (d *debugRuntime) SetStopOnEntry(stopOnEntry bool) {
	if d == nil || d.closed.Load() {
		return
	}
	d.stopOnEntry.Store(stopOnEntry)
	d.refreshActive()
}

func (d *debugRuntime) SetBreakpoint(id string) {
	if d == nil || d.closed.Load() {
		return
	}
	id = normalizeDebugID(id)
	if id == "" {
		return
	}
	d.breakpointsMu.Lock()
	d.breakpoints[id] = struct{}{}
	d.breakpointsActive.Store(len(d.breakpoints) > 0)
	d.breakpointsMu.Unlock()
	d.refreshActive()
}

func (d *debugRuntime) ClearBreakpoint(id string) {
	if d == nil {
		return
	}
	id = normalizeDebugID(id)
	if id == "" {
		return
	}
	d.breakpointsMu.Lock()
	delete(d.breakpoints, id)
	d.breakpointsActive.Store(len(d.breakpoints) > 0)
	d.breakpointsMu.Unlock()
	d.refreshActive()
}

func (d *debugRuntime) ClearAllBreakpoints() {
	if d == nil {
		return
	}
	d.breakpointsMu.Lock()
	d.breakpoints = map[string]struct{}{}
	d.breakpointsActive.Store(false)
	d.breakpointsMu.Unlock()
	d.refreshActive()
}

func (d *debugRuntime) hasBreakpoint(id string) bool {
	if d == nil || !d.breakpointsActive.Load() {
		return false
	}
	id = normalizeDebugID(id)
	if id == "" {
		return false
	}
	d.breakpointsMu.RLock()
	_, ok := d.breakpoints[id]
	d.breakpointsMu.RUnlock()
	return ok
}

func (d *debugRuntime) currentDepth() int {
	if d == nil {
		return 0
	}
	d.pauseMu.Lock()
	defer d.pauseMu.Unlock()
	if d.paused {
		return d.pauseState.Depth
	}
	return int(d.stackDepth.Load())
}

func (d *debugRuntime) PushFrame(blockName string, sourceFile string, sourceLine int) {
	if d == nil || d.closed.Load() {
		return
	}
	frame := StackFrame{
		BlockName:  strings.TrimSpace(blockName),
		SourceFile: strings.TrimSpace(sourceFile),
		SourceLine: sourceLine,
	}
	d.stackMu.Lock()
	if len(d.stack) == debugMaxStackFrames {
		copy(d.stack, d.stack[1:])
		d.stack[len(d.stack)-1] = frame
	} else {
		d.stack = append(d.stack, frame)
	}
	d.stackDepth.Add(1)
	d.stackMu.Unlock()
}

func (d *debugRuntime) PopFrame() {
	if d == nil {
		return
	}
	d.stackMu.Lock()
	if n := len(d.stack); n > 0 {
		d.stack = d.stack[:n-1]
	}
	depth := int(d.stackDepth.Load())
	if depth > 0 {
		depth--
	}
	d.stackDepth.Store(int32(depth))
	d.stackMu.Unlock()
}

func (d *debugRuntime) GetStack() []StackFrame {
	if d == nil {
		return nil
	}
	d.stackMu.RLock()
	defer d.stackMu.RUnlock()
	if len(d.stack) == 0 {
		return nil
	}
	stack := make([]StackFrame, len(d.stack))
	copy(stack, d.stack)
	return stack
}

func (d *debugRuntime) setCurrentFrameLocation(sourceFile string, sourceLine int) {
	if d == nil {
		return
	}
	d.stackMu.Lock()
	if n := len(d.stack); n > 0 {
		if sourceFile != "" {
			d.stack[n-1].SourceFile = strings.TrimSpace(sourceFile)
		}
		if sourceLine > 0 {
			d.stack[n-1].SourceLine = sourceLine
		}
	}
	d.stackMu.Unlock()
}

func (d *debugRuntime) armStep(mode debugStepMode, depth int) {
	if d == nil || d.closed.Load() {
		return
	}
	d.pauseRequested.Store(false)
	d.stepMode.Store(uint32(mode))
	d.stepDepth.Store(int32(depth))
	d.refreshActive()
}

func (d *debugRuntime) armResumeSkipFromPause() {
	if d == nil {
		return
	}
	d.pauseMu.Lock()
	defer d.pauseMu.Unlock()
	if !d.paused {
		return
	}
	id := normalizeDebugID(d.pauseState.ID)
	if id == "" {
		d.resumeSkip = debugPauseState{}
		d.hasResumeSkip = false
		return
	}
	d.resumeSkip = debugPauseState{ID: id, Depth: d.pauseState.Depth}
	d.hasResumeSkip = true
}

func (d *debugRuntime) shouldSkipResumedPause(id string, depth int) bool {
	if d == nil {
		return false
	}
	d.pauseMu.Lock()
	defer d.pauseMu.Unlock()
	if !d.hasResumeSkip {
		return false
	}
	if d.resumeSkip.ID == id && d.resumeSkip.Depth == depth {
		d.hasResumeSkip = false
		d.resumeSkip = debugPauseState{}
		return true
	}
	d.hasResumeSkip = false
	d.resumeSkip = debugPauseState{}
	return false
}

func (d *debugRuntime) resumeLocked() {
	if d.resumeCh != nil {
		close(d.resumeCh)
		d.resumeCh = nil
	}
	d.paused = false
	d.pausedCh = make(chan struct{})
}

func (d *debugRuntime) resumeIfPaused() {
	if d == nil {
		return
	}
	d.pauseMu.Lock()
	if d.paused {
		d.resumeLocked()
	}
	d.pauseMu.Unlock()
}

func (d *debugRuntime) StepInto() {
	if d == nil {
		return
	}
	d.armResumeSkipFromPause()
	d.armStep(debugStepModeInto, d.currentDepth())
	d.resumeIfPaused()
}

func (d *debugRuntime) StepNext() {
	if d == nil {
		return
	}
	d.armResumeSkipFromPause()
	d.armStep(debugStepModeNext, d.currentDepth())
	d.resumeIfPaused()
}

func (d *debugRuntime) StepOut() {
	if d == nil {
		return
	}
	d.armResumeSkipFromPause()
	d.armStep(debugStepModeOut, d.currentDepth())
	d.resumeIfPaused()
}

func (d *debugRuntime) Continue() {
	if d == nil {
		return
	}
	d.pauseRequested.Store(false)
	d.stepMode.Store(uint32(debugStepModeNone))
	d.refreshActive()
	d.resumeIfPaused()
}

func (d *debugRuntime) Pause() {
	if d == nil || d.closed.Load() {
		return
	}
	d.pauseRequested.Store(true)
	d.refreshActive()
}

func (d *debugRuntime) Close() {
	if d == nil {
		return
	}
	d.closeOnce.Do(func() {
		d.closed.Store(true)
		d.pauseRequested.Store(false)
		d.stopOnEntry.Store(false)
		d.stepMode.Store(uint32(debugStepModeNone))
		d.breakpointsActive.Store(false)
		d.stackDepth.Store(0)
		d.breakpointsMu.Lock()
		d.breakpoints = map[string]struct{}{}
		d.breakpointsMu.Unlock()
		d.stackMu.Lock()
		d.stack = nil
		d.stackMu.Unlock()
		d.refreshActive()
		close(d.closeCh)
		d.resumeIfPaused()
	})
}

func (d *debugRuntime) Disconnect() {
	d.Close()
}

func (d *debugRuntime) shouldPause(id string, depth int) (string, bool) {
	if d == nil || d.closed.Load() || !d.active.Load() {
		return "", false
	}
	id = normalizeDebugID(id)
	if d.stopOnEntry.CompareAndSwap(true, false) {
		d.refreshActive()
		return "entry", true
	}
	if d.pauseRequested.CompareAndSwap(true, false) {
		d.refreshActive()
		return "pause", true
	}
	if d.shouldSkipResumedPause(id, depth) {
		return "", false
	}
	if d.hasBreakpoint(id) {
		return "breakpoint", true
	}
	switch debugStepMode(d.stepMode.Load()) {
	case debugStepModeInto:
		d.stepMode.Store(uint32(debugStepModeNone))
		d.refreshActive()
		return "step", true
	case debugStepModeNext:
		if depth <= int(d.stepDepth.Load()) {
			d.stepMode.Store(uint32(debugStepModeNone))
			d.refreshActive()
			return "step", true
		}
	case debugStepModeOut:
		if depth < int(d.stepDepth.Load()) {
			d.stepMode.Store(uint32(debugStepModeNone))
			d.refreshActive()
			return "step", true
		}
	}
	return "", false
}

func (d *debugRuntime) pause(state debugPauseState) {
	if d == nil || d.closed.Load() {
		return
	}
	d.pauseMu.Lock()
	if d.closed.Load() {
		d.pauseMu.Unlock()
		return
	}
	resumeCh := make(chan struct{})
	pausedCh := d.pausedCh
	d.pauseState = state
	d.paused = true
	d.resumeCh = resumeCh
	d.pauseMu.Unlock()
	onPauseWait, onPauseResume := d.pauseHooks()
	if onPauseWait != nil {
		onPauseWait()
	}
	close(pausedCh)

	select {
	case <-resumeCh:
	case <-d.closeCh:
	}
	if onPauseResume != nil {
		onPauseResume()
	}

	d.pauseMu.Lock()
	if d.resumeCh == resumeCh {
		d.resumeCh = nil
	}
	if d.paused {
		d.paused = false
		d.pausedCh = make(chan struct{})
	}
	d.pauseMu.Unlock()
}

func (d *debugRuntime) DebugLine(id string) {
	d.DebugLineWithDepth(id, int(d.stackDepth.Load()))
}

func (d *debugRuntime) DebugLineWithDepth(id string, depth int) {
	if d == nil || d.closed.Load() || !d.active.Load() {
		return
	}
	id = normalizeDebugID(id)
	reason, ok := d.shouldPause(id, depth)
	if !ok {
		return
	}
	d.pause(debugPauseState{ID: id, Reason: reason, Depth: depth})
}

var defaultDebugRuntime = newDebugRuntime(false)

func debugLine(id string) {
	defaultDebugRuntime.DebugLine(id)
}

func debugLineWithSnapshot(id string, vars []DebugSnapshotVariable) {
	id = normalizeDebugID(id)
	emitDebugSnapshot(id, vars)
	defaultDebugRuntime.DebugLine(id)
}

func PushFrame(blockName string, sourceFile string, sourceLine int) {
	defaultDebugRuntime.PushFrame(blockName, sourceFile, sourceLine)
}

func PopFrame() {
	defaultDebugRuntime.PopFrame()
}

func GetStack() []StackFrame {
	return defaultDebugRuntime.GetStack()
}

func SetBreakpoint(id string) {
	defaultDebugRuntime.SetBreakpoint(id)
}

func ClearBreakpoint(id string) {
	defaultDebugRuntime.ClearBreakpoint(id)
}

func ClearAllBreakpoints() {
	defaultDebugRuntime.ClearAllBreakpoints()
}

func StepNext() {
	defaultDebugRuntime.StepNext()
}

func StepInto() {
	defaultDebugRuntime.StepInto()
}

func StepOut() {
	defaultDebugRuntime.StepOut()
}

func Continue() {
	defaultDebugRuntime.Continue()
}

func Pause() {
	defaultDebugRuntime.Pause()
}

func Disconnect() {
	defaultDebugRuntime.Disconnect()
}

func Close() {
	defaultDebugRuntime.Close()
}
