// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"time"
)

// Runner executes one deterministic scan step at a time.
//
// The scan path is allocation-free as long as user hooks and builtins are.
type Runner struct {
	Mem      Memory
	Clock    Clock
	testStep func(*Runner)
}

func runnerStepNowNS(r *Runner) int64 {
	if r != nil && r.Clock != nil {
		return int64(r.Clock.Now())
	}
	return time.Now().UnixNano()
}

func runnerRecordCycleStats(r *Runner) int64 {
	if r == nil {
		return 1
	}
	nowNS := runnerStepNowNS(r)
	cycleNS := int64(1)
	if r.Mem.SCLH_LastStepNS > 0 {
		cycleNS = nowNS - r.Mem.SCLH_LastStepNS
		if cycleNS <= 0 {
			cycleNS = 1
		}
	}
	r.Mem.SCLH_LastStepNS = nowNS
	r.Mem.SCLH_CycleLastNS = cycleNS
	if r.Mem.SCLH_CycleShortestNS == 0 || cycleNS < r.Mem.SCLH_CycleShortestNS {
		r.Mem.SCLH_CycleShortestNS = cycleNS
	}
	if cycleNS > r.Mem.SCLH_CycleLongestNS {
		r.Mem.SCLH_CycleLongestNS = cycleNS
	}
	r.Mem.SCLH_CycleWindowNS += cycleNS
	r.Mem.SCLH_CycleWindowCount++
	return cycleNS
}

func (r *Runner) Step() {
	_ = runnerRecordCycleStats(r)
	if r.testStep != nil {
		r.testStep(r)
		return
	}
	OB_OB1(&r.Mem)
}
