// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"fmt"
	"plc-autogen/builtins"
	"testing"
)

type TestObservationHooks interface {
	OnTestStart(TestStartEvent)
	OnStep(TestStepEvent)
	OnAssert(TestAssertEvent)
	OnTestComplete(TestCompleteEvent)
}

type TestStartEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
}

type TestStepEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	ClockNow   TIME
}

type TestAssertEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	Passed     bool
	Condition  string
	Operator   string
	Got        string
	Expected   string
	Tolerance  string
	ClockNow   TIME
}

type TestCompleteEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Passed     bool
	Steps      int
	ClockNow   TIME
}

type TestRuntimeContext struct {
	Hooks TestObservationHooks
}

func NewTestRuntimeContext(hooks TestObservationHooks) *TestRuntimeContext {
	return &TestRuntimeContext{Hooks: hooks}
}

func observeTestStart(ctx *TestRuntimeContext, event TestStartEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestStart(event)
	}
}

func observeTestStep(ctx *TestRuntimeContext, event TestStepEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnStep(event)
	}
}

func observeTestAssert(ctx *TestRuntimeContext, event TestAssertEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnAssert(event)
	}
}

func observeTestComplete(ctx *TestRuntimeContext, event TestCompleteEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestComplete(event)
	}
}

func testObservationString(value any) string {
	return fmt.Sprint(value)
}

func resetGeneratedTestBuiltinsState() {
	builtins.ResetGeneratedTestState()
}

func resetGeneratedTestRuntimeState() {
	resetGeneratedTestBuiltinsState()

}

func TestUserCase001_TestSimple(t *testing.T) {
	t.Parallel()
	runTestUserCase001_TestSimple(t, nil)
}

func runTestUserCase001_TestSimple(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 1, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 1, Column: 1, Passed: passed, Steps: 7, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 2, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_EStop = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 3, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_EStop = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 4, Column: 5, Step: 3, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_Fault = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 5, Column: 5, Step: 4, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bRobot_EStop = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 6, Column: 5, Step: 5, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bRobot_Fault = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 8, Column: 5, Step: 6, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(2000)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 10, Column: 5, Step: 7, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_bSystemSafetyConditionMet
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_bSystemSafetyConditionMet == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "test_simple", StableID: "scltest:02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:L1:C1:test_simple", SourcePath: "02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest", Line: 10, Column: 5, Step: 7, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_bSystemSafetyConditionMet = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at 02_PLC程序/通用ST程序及变量表/Test/basic_test.scltest:10:5 step 7: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}
