// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"github.com/awcullen/opcua/client"
	"github.com/awcullen/opcua/ua"
	"net"
	"plc-autogen/runtime"
	"reflect"
	"strings"
	"testing"
	"time"
)

func TestBuildMemoryTagIndex(t *testing.T) {
	type sample struct {
		Top bool
		DB  struct {
			Inner int16
		}
		hidden bool
	}

	tags := buildMemoryTagIndex(reflect.TypeOf(sample{}))
	if len(tags) < 2 {
		t.Fatalf("buildMemoryTagIndex() len=%d, want >=2", len(tags))
	}
	var hasInner bool
	var hasTop bool
	for _, tag := range tags {
		if tag.Name == "DB.Inner" {
			hasInner = true
		}
		if tag.Name == "Top" {
			hasTop = true
		}
	}
	if !hasInner || !hasTop {
		t.Fatalf("missing expected tags in %+v", tags)
	}
}

func TestTUISearchRendering(t *testing.T) {
	m := model{
		tags:   []memoryTag{{Name: "DB_Main.Counter"}, {Name: "System.Flag"}},
		values: []string{"1", "true"},
		height: 20,
		width:  80,
	}
	m.applyFilter()
	m.query = "db"
	m.applyFilter()
	view := m.View()
	if !strings.Contains(strings.ToLower(view), "db_main.counter") {
		t.Fatalf("view missing filtered tag: %q", view)
	}
	if strings.Contains(strings.ToLower(view), "system.flag") {
		t.Fatalf("view still contains non-matching tag: %q", view)
	}
}

func TestOPCUAServer_AnonymousBrowseRead(t *testing.T) {

	snapshot := &sharedMemory{}
	state := newRuntimeState(snapshot, 0)
	state.Step()

	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	if len(tags) == 0 {
		t.Skip("generated memory has no scalar tags")
	}

	port := freeTCPPort(t)
	srv, err := startOPCUAServer(snapshot, tags, nil, port)
	if err != nil {
		t.Fatalf("startOPCUAServer() error: %v", err)
	}
	defer func() {
		_ = srv.Close()
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	endpoint := fmt.Sprintf("opc.tcp://127.0.0.1:%d", port)
	ch, err := dialOPCUATestClient(ctx, endpoint)
	if err != nil {
		t.Fatalf("Dial() error: %v", err)
	}
	defer func() {
		_ = ch.Close(ctx)
	}()

	browseResp, err := ch.Browse(ctx, &ua.BrowseRequest{
		NodesToBrowse: []ua.BrowseDescription{{
			NodeID:          ua.ParseNodeID("ns=2;s=" + opcuaMemoryFolderID),
			BrowseDirection: ua.BrowseDirectionForward,
			ReferenceTypeID: ua.ReferenceTypeIDOrganizes,
			IncludeSubtypes: true,
			ResultMask:      uint32(ua.BrowseResultMaskAll),
		}},
	})
	if err != nil {
		t.Fatalf("Browse() error: %v", err)
	}
	if len(browseResp.Results) != 1 {
		t.Fatalf("Browse() results=%d, want 1", len(browseResp.Results))
	}
	if !browseResp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Browse() status=%v, want Good", browseResp.Results[0].StatusCode)
	}
	if len(browseResp.Results[0].References) == 0 {
		t.Fatal("Browse() returned no memory tag references")
	}

	target := ua.ParseNodeID("ns=2;s=" + opcuaMemoryFolderID + "." + tags[0].Name)
	readResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: target, AttributeID: ua.AttributeIDValue}}})
	if err != nil {
		t.Fatalf("Read() error: %v", err)
	}
	if len(readResp.Results) != 1 {
		t.Fatalf("Read() results=%d, want 1", len(readResp.Results))
	}
	if !readResp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Read() status=%v, want Good", readResp.Results[0].StatusCode)
	}
	if readResp.Results[0].Value == nil {
		t.Fatal("Read() returned nil value")
	}

	accessResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: target, AttributeID: ua.AttributeIDAccessLevel}}})
	if err != nil {
		t.Fatalf("Read() access level error: %v", err)
	}
	if len(accessResp.Results) != 1 {
		t.Fatalf("Read() access level results=%d, want 1", len(accessResp.Results))
	}
	accessLevel, ok := accessResp.Results[0].Value.(byte)
	if !ok {
		t.Fatalf("AccessLevel value type=%T, want byte", accessResp.Results[0].Value)
	}
	if accessLevel&(ua.AccessLevelsCurrentRead|ua.AccessLevelsCurrentWrite) != (ua.AccessLevelsCurrentRead | ua.AccessLevelsCurrentWrite) {
		t.Skipf("generated runtime OPC memory nodes are read-only in this build (access level=%#x)", accessLevel)
	}
}

func TestOPCUAServer_AnonymousWriteValidation(t *testing.T) {

	snapshot := &sharedMemory{}
	newRuntimeState(snapshot, 0)

	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	tag, goodValue, badTypeValue, badRangeValue, ok := findWritableScalarTag(reflect.TypeOf(plcruntime.Memory{}), tags)
	if !ok {
		t.Skip("generated memory has no writable scalar tags suitable for validation")
	}
	port := freeTCPPort(t)
	srv, err := startOPCUAServer(snapshot, tags, nil, port)
	if err != nil {
		t.Fatalf("startOPCUAServer() error: %v", err)
	}
	defer func() {
		_ = srv.Close()
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	endpoint := fmt.Sprintf("opc.tcp://127.0.0.1:%d", port)
	ch, err := dialOPCUATestClient(ctx, endpoint)
	if err != nil {
		t.Fatalf("Dial() error: %v", err)
	}
	defer func() {
		_ = ch.Close(ctx)
	}()

	target := ua.ParseNodeID("ns=2;s=" + opcuaMemoryFolderID + "." + tag.Name)
	writeResp, err := ch.Write(ctx, &ua.WriteRequest{NodesToWrite: []ua.WriteValue{{
		NodeID:      target,
		AttributeID: ua.AttributeIDValue,
		Value:       ua.NewDataValue(goodValue, 0, time.Time{}, 0, time.Time{}, 0),
	}}})
	if err != nil {
		t.Skipf("generated runtime OPC writes unavailable in this build: %v", err)
	}
	if len(writeResp.Results) != 1 {
		t.Fatalf("Write() good value results=%v", writeResp.Results)
	}
	if writeResp.Results[0] == ua.BadUserAccessDenied || writeResp.Results[0] == ua.BadNotWritable {
		t.Skipf("generated runtime OPC writes unavailable in this build: %v", writeResp.Results[0])
	}
	if !writeResp.Results[0].IsGood() {
		t.Fatalf("Write() good value status=%v", writeResp.Results)
	}
	if got := readOPCUATagValue(snapshot, tag.Index); fmt.Sprint(got) != fmt.Sprint(goodValue) {
		t.Fatalf("live memory value=%v, want %v", got, goodValue)
	}

	readResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: target, AttributeID: ua.AttributeIDValue}}})
	if err != nil {
		t.Fatalf("Read() after write error: %v", err)
	}
	if len(readResp.Results) != 1 || !readResp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Read() after write status=%v", readResp.Results)
	}
	if fmt.Sprint(readResp.Results[0].Value) != fmt.Sprint(goodValue) {
		t.Fatalf("OPC readback=%v, want %v", readResp.Results[0].Value, goodValue)
	}

	typeResp, err := ch.Write(ctx, &ua.WriteRequest{NodesToWrite: []ua.WriteValue{{
		NodeID:      target,
		AttributeID: ua.AttributeIDValue,
		Value:       ua.NewDataValue(badTypeValue, 0, time.Time{}, 0, time.Time{}, 0),
	}}})
	if err != nil {
		t.Fatalf("Write() bad type error: %v", err)
	}
	if len(typeResp.Results) != 1 || typeResp.Results[0] != ua.BadTypeMismatch {
		t.Fatalf("Write() bad type status=%v, want %v", typeResp.Results, ua.BadTypeMismatch)
	}

	if badRangeValue != nil {
		rangeResp, err := ch.Write(ctx, &ua.WriteRequest{NodesToWrite: []ua.WriteValue{{
			NodeID:      target,
			AttributeID: ua.AttributeIDValue,
			Value:       ua.NewDataValue(badRangeValue, 0, time.Time{}, 0, time.Time{}, 0),
		}}})
		if err != nil {
			t.Fatalf("Write() bad range error: %v", err)
		}
		if len(rangeResp.Results) != 1 || rangeResp.Results[0] != ua.BadOutOfRange {
			t.Fatalf("Write() bad range status=%v, want %v", rangeResp.Results, ua.BadOutOfRange)
		}
	}
}

func findWritableScalarTag(memType reflect.Type, tags []memoryTag) (memoryTag, any, any, any, bool) {
	for _, tag := range tags {
		if len(tag.Index) == 0 {
			continue
		}
		field := memType.FieldByIndex(tag.Index)
		switch field.Type.Kind() {
		case reflect.Bool:
			return tag, true, "bad", nil, true
		case reflect.Int8:
			return tag, int8(7), "bad", int16(1000), true
		case reflect.Int16:
			return tag, int16(7), "bad", int32(40000), true
		case reflect.Int32:
			return tag, int32(7), "bad", int64(1 << 40), true
		case reflect.Int, reflect.Int64:
			return tag, reflect.ValueOf(int64(7)).Convert(field.Type).Interface(), "bad", nil, true
		case reflect.Uint8:
			return tag, uint8(7), "bad", int16(-1), true
		case reflect.Uint16:
			return tag, uint16(7), "bad", int32(-1), true
		case reflect.Uint32:
			return tag, uint32(7), "bad", int64(-1), true
		case reflect.Uint, reflect.Uint64, reflect.Uintptr:
			return tag, reflect.ValueOf(uint64(7)).Convert(field.Type).Interface(), "bad", int16(-1), true
		case reflect.Float32:
			return tag, float32(7.5), "bad", nil, true
		case reflect.Float64:
			return tag, float64(7.5), "bad", nil, true
		case reflect.String:
			return tag, "written", int16(7), nil, true
		}
	}
	return memoryTag{}, nil, nil, nil, false
}

func dialOPCUATestClient(ctx context.Context, endpoint string) (*client.Client, error) {
	var lastErr error
	for attempt := 0; attempt < 20; attempt++ {
		ch, err := client.Dial(ctx, endpoint, client.WithInsecureSkipVerify())
		if err == nil {
			return ch, nil
		}
		lastErr = err
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(100 * time.Millisecond):
		}
	}
	return nil, fmt.Errorf("dial OPC-UA endpoint %s failed: %w", endpoint, lastErr)
}

func freeTCPPort(t *testing.T) int {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("net.Listen() error: %v", err)
	}
	defer ln.Close()
	addr, ok := ln.Addr().(*net.TCPAddr)
	if !ok {
		t.Fatalf("unexpected listener address type %T", ln.Addr())
	}
	return addr.Port
}
