# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4d37b06
_src_path: https://github.com/gotofritz/copier-python-template.git
author_email: gotofritz@users.noreply.github.com
author_name: fubai
cli: true
org_name: fubai
package_name: plc_pm_tool
project_description: PLC项目看板 + 变更管理 + 标准化管理工具
project_name: PLC项目管理工具
project_url: https://github.com/fubai/plc-pm-tool
python_version: '3.11'
with_conventional_commits: true
