// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"github.com/awcullen/opcua/server"
	"github.com/awcullen/opcua/ua"
	"github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"math"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"plc-autogen/runtime"
	"reflect"
	"sort"
	"strings"
	"sync"
	"time"
	"unsafe"
)

type memoryTag struct {
	Name  string
	Index []int
}

type sharedMemory struct {
	mu      sync.RWMutex
	mem     plcruntime.Memory
	runtime *runtimeState
}

func (s *sharedMemory) Set(mem plcruntime.Memory) {
	s.mu.Lock()
	s.mem = mem
	s.mu.Unlock()
}

func (s *sharedMemory) AttachRuntime(state *runtimeState) {
	if s == nil {
		return
	}
	s.runtime = state
}

func (s *sharedMemory) runtimeState() *runtimeState {
	if s == nil {
		return nil
	}
	return s.runtime
}

func (s *sharedMemory) Snapshot() plcruntime.Memory {
	if rt := s.runtimeState(); rt != nil {
		return rt.MemorySnapshot()
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.mem
}

func (s *sharedMemory) Write(index []int, value any) (any, ua.StatusCode) {
	if s == nil || len(index) == 0 {
		return nil, ua.BadNodeIDUnknown
	}
	if rt := s.runtimeState(); rt != nil {
		if status := rt.WriteMemoryValue(index, value); status.IsBad() {
			return nil, status
		}
		return readOPCUATagValue(s, index), ua.Good
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	target := reflect.ValueOf(&s.mem).Elem().FieldByIndex(index)
	if status := setReflectValue(target, value); status.IsBad() {
		return nil, status
	}
	return readReflectValue(target), ua.Good
}

const (
	opcuaNamespaceURI      = "urn:plc-runtime:opcua"
	opcuaRootNodeID        = "PLC"
	opcuaMemoryFolderID    = "PLC.Memory"
	opcuaDebugFolderID     = "PLC.Debug"
	opcuaSnapshotsFolderID = "PLC.Debug.Snapshots"
	opcuaDefaultHostName   = "127.0.0.1"
)

const runtimeHasDebugSnapshotOPC = false

func opcuaWritableRolePermissions() []ua.RolePermissionType {
	permissions := ua.PermissionTypeBrowse | ua.PermissionTypeRead | ua.PermissionTypeWrite | ua.PermissionTypeReadHistory
	return []ua.RolePermissionType{
		{RoleID: ua.ObjectIDWellKnownRoleAnonymous, Permissions: permissions},
		{RoleID: ua.ObjectIDWellKnownRoleAuthenticatedUser, Permissions: permissions},
	}
}

type opcuaServer struct {
	srv       *server.Server
	endpoint  string
	done      chan error
	cleanup   func()
	closeOnce sync.Once
}

func (s *opcuaServer) EndpointURL() string {
	if s == nil {
		return ""
	}
	return s.endpoint
}

func (s *opcuaServer) Close() error {
	if s == nil {
		return nil
	}
	var closeErr error
	s.closeOnce.Do(func() {
		if s.srv != nil {
			closeErr = s.srv.Close()
		}
		if s.done != nil {
			<-s.done
		}
		if s.cleanup != nil {
			s.cleanup()
		}
	})
	return closeErr
}

func startOPCUAServer(snapshot *sharedMemory, tags []memoryTag, debugSnapshots *debugSnapshotStore, port int) (*opcuaServer, error) {
	if port <= 0 {
		return nil, nil
	}

	certPath, keyPath, cleanup, err := writeOPCUASelfSignedCert()
	if err != nil {
		return nil, err
	}

	endpoint := fmt.Sprintf("opc.tcp://%s:%d", opcuaDefaultHostName, port)
	appName := "plc-run"
	app := ua.ApplicationDescription{
		ApplicationURI:      "urn:plc-run:opcua",
		ProductURI:          "urn:plc-run",
		ApplicationName:     ua.LocalizedText{Text: appName, Locale: "en"},
		ApplicationType:     ua.ApplicationTypeServer,
		DiscoveryProfileURI: "",
		DiscoveryURLs:       []string{endpoint},
	}

	srv, err := server.New(
		app,
		certPath,
		keyPath,
		endpoint,
		server.WithAnonymousIdentity(true),
		server.WithSecurityPolicyNone(true),
		server.WithInsecureSkipVerify(),
		server.WithServerDiagnostics(false),
	)
	if err != nil {
		cleanup()
		return nil, err
	}
	if err := installOPCUANodes(srv, snapshot, tags, debugSnapshots); err != nil {
		_ = srv.Close()
		cleanup()
		return nil, err
	}

	state := &opcuaServer{
		srv:      srv,
		endpoint: endpoint,
		done:     make(chan error, 1),
		cleanup:  cleanup,
	}
	go func() {
		err := srv.ListenAndServe()
		if err != nil && !errors.Is(err, ua.BadServerHalted) {
			state.done <- err
			return
		}
		state.done <- nil
	}()
	if err := waitForTCPReady(endpoint, 8*time.Second); err != nil {
		_ = state.Close()
		return nil, err
	}
	return state, nil
}

func waitForTCPReady(endpoint string, timeout time.Duration) error {
	addr := strings.TrimPrefix(endpoint, "opc.tcp://")
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", addr, 100*time.Millisecond)
		if err == nil {
			_ = conn.Close()
			return nil
		}
		time.Sleep(50 * time.Millisecond)
	}
	return fmt.Errorf("timeout waiting for OPC-UA listener at %s", endpoint)
}

func writeOPCUASelfSignedCert() (certPath string, keyPath string, cleanup func(), err error) {
	tmpDir, err := os.MkdirTemp("", "plc-run-opcua-*")
	if err != nil {
		return "", "", nil, err
	}
	cleanup = func() {
		_ = os.RemoveAll(tmpDir)
	}

	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		cleanup()
		return "", "", nil, err
	}
	now := time.Now().UTC()
	tpl := &x509.Certificate{
		SerialNumber:          big.NewInt(now.UnixNano()),
		Subject:               pkix.Name{CommonName: "plc-run-opcua"},
		NotBefore:             now.Add(-time.Hour),
		NotAfter:              now.Add(24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames:              []string{"localhost"},
		IPAddresses:           []net.IP{net.ParseIP("127.0.0.1")},
	}
	der, err := x509.CreateCertificate(rand.Reader, tpl, tpl, &priv.PublicKey, priv)
	if err != nil {
		cleanup()
		return "", "", nil, err
	}

	certPath = filepath.Join(tmpDir, "server.crt")
	keyPath = filepath.Join(tmpDir, "server.key")
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(priv)})
	if err := os.WriteFile(certPath, certPEM, 0o600); err != nil {
		cleanup()
		return "", "", nil, err
	}
	if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
		cleanup()
		return "", "", nil, err
	}
	return certPath, keyPath, cleanup, nil
}

func installOPCUANodes(srv *server.Server, snapshot *sharedMemory, tags []memoryTag, debugSnapshots *debugSnapshotStore) error {
	nm := srv.NamespaceManager()
	ns := nm.Add(opcuaNamespaceURI)
	rootID := ua.NewNodeIDString(ns, opcuaRootNodeID)
	memoryFolderID := ua.NewNodeIDString(ns, opcuaMemoryFolderID)

	root := server.NewObjectNode(
		srv,
		rootID,
		ua.NewQualifiedName(ns, "PLC"),
		ua.LocalizedText{Text: "PLC", Locale: "en"},
		ua.LocalizedText{Text: "PLC Runtime Root", Locale: "en"},
		nil,
		[]ua.Reference{
			{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ObjectIDObjectsFolder)},
			{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
		},
		0,
	)
	memoryFolder := server.NewObjectNode(
		srv,
		memoryFolderID,
		ua.NewQualifiedName(ns, "Memory"),
		ua.LocalizedText{Text: "Memory", Locale: "en"},
		ua.LocalizedText{Text: "PLC Runtime Memory", Locale: "en"},
		nil,
		[]ua.Reference{
			{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(rootID)},
			{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
		},
		0,
	)

	nodes := []server.Node{root, memoryFolder}
	if runtimeHasDebugSnapshotOPC && debugSnapshots != nil {
		debugFolderID := ua.NewNodeIDString(ns, opcuaDebugFolderID)
		snapshotsFolderID := ua.NewNodeIDString(ns, opcuaSnapshotsFolderID)
		debugFolder := server.NewObjectNode(
			srv,
			debugFolderID,
			ua.NewQualifiedName(ns, "Debug"),
			ua.LocalizedText{Text: "Debug", Locale: "en"},
			ua.LocalizedText{Text: "PLC Debug Data", Locale: "en"},
			nil,
			[]ua.Reference{
				{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(rootID)},
				{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
			},
			0,
		)
		snapshotsFolder := server.NewObjectNode(
			srv,
			snapshotsFolderID,
			ua.NewQualifiedName(ns, "Snapshots"),
			ua.LocalizedText{Text: "Snapshots", Locale: "en"},
			ua.LocalizedText{Text: "Paused statement snapshots", Locale: "en"},
			nil,
			[]ua.Reference{
				{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(debugFolderID)},
				{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
			},
			0,
		)
		nodes = append(nodes, debugFolder, snapshotsFolder)
		for _, entry := range debugSnapshots.Statements() {
			debugID := strings.TrimSpace(entry.DebugID)
			if debugID == "" {
				continue
			}
			lineFolderID := ua.NewNodeIDString(ns, opcuaSnapshotsFolderID+"."+debugID)
			lineFolder := server.NewObjectNode(
				srv,
				lineFolderID,
				ua.NewQualifiedName(ns, debugID),
				ua.LocalizedText{Text: debugID, Locale: "en"},
				ua.LocalizedText{Text: "Statement snapshot", Locale: "en"},
				nil,
				[]ua.Reference{
					{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(snapshotsFolderID)},
					{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
				},
				0,
			)
			nodes = append(nodes, lineFolder)
			seen := map[string]struct{}{}
			for _, ref := range entry.Variables {
				name := strings.TrimSpace(ref.Name)
				if name == "" {
					continue
				}
				key := strings.ToUpper(name)
				if _, ok := seen[key]; ok {
					continue
				}
				seen[key] = struct{}{}
				varName := name
				varDebugID := debugID
				variableNodeID := ua.NewNodeIDString(ns, opcuaSnapshotsFolderID+"."+debugID+"."+name)
				variableNode := server.NewVariableNode(
					srv,
					variableNodeID,
					ua.NewQualifiedName(ns, name),
					ua.LocalizedText{Text: name, Locale: "en"},
					ua.LocalizedText{Text: name, Locale: "en"},
					nil,
					[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(lineFolderID)}},
					ua.NewDataValue(debugSnapshots.ReadValue(varDebugID, varName), 0, time.Now(), 0, time.Now(), 0),
					ua.DataTypeIDBaseDataType,
					ua.ValueRankScalar,
					[]uint32{},
					ua.AccessLevelsCurrentRead,
					0,
					false,
					nil,
				)
				variableNode.SetReadValueHandler(func(_ *server.Session, _ ua.ReadValueID) ua.DataValue {
					return ua.NewDataValue(debugSnapshots.ReadValue(varDebugID, varName), 0, time.Now(), 0, time.Now(), 0)
				})
				nodes = append(nodes, variableNode)
			}
		}
	}
	writablePermissions := opcuaWritableRolePermissions()
	for _, tag := range tags {
		tagNodeID := ua.NewNodeIDString(ns, opcuaMemoryFolderID+"."+tag.Name)
		tagBrowseName := ua.NewQualifiedName(ns, tag.Name)
		tagDisplayName := ua.LocalizedText{Text: tag.Name, Locale: "en"}
		index := append([]int(nil), tag.Index...)
		v := server.NewVariableNode(
			srv,
			tagNodeID,
			tagBrowseName,
			tagDisplayName,
			tagDisplayName,
			writablePermissions,
			[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(memoryFolderID)}},
			ua.NewDataValue(readOPCUATagValue(snapshot, index), 0, time.Now(), 0, time.Now(), 0),
			ua.DataTypeIDBaseDataType,
			ua.ValueRankScalar,
			[]uint32{},
			ua.AccessLevelsCurrentRead|ua.AccessLevelsCurrentWrite,
			0,
			false,
			nil,
		)
		v.SetReadValueHandler(func(_ *server.Session, _ ua.ReadValueID) ua.DataValue {
			return ua.NewDataValue(readOPCUATagValue(snapshot, index), 0, time.Now(), 0, time.Now(), 0)
		})
		v.SetWriteValueHandler(func(_ *server.Session, req ua.WriteValue) (ua.DataValue, ua.StatusCode) {
			written, status := writeOPCUATagValue(snapshot, index, req.Value.Value)
			if status.IsBad() {
				return req.Value, status
			}
			return ua.NewDataValue(written, 0, time.Now(), 0, time.Now(), 0), ua.Good
		})
		nodes = append(nodes, v)
	}

	return nm.AddNodes(nodes...)
}

func readOPCUATagValue(snapshot *sharedMemory, index []int) any {
	if snapshot == nil || len(index) == 0 {
		return ""
	}
	v := reflect.ValueOf(snapshot.Snapshot()).FieldByIndex(index)
	return readReflectValue(v)
}

func writeOPCUATagValue(snapshot *sharedMemory, index []int, value any) (any, ua.StatusCode) {
	if snapshot == nil {
		return nil, ua.BadNotWritable
	}
	return snapshot.Write(index, value)
}

func readReflectValue(v reflect.Value) any {
	if !v.IsValid() {
		return ""
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return ""
		}
		v = v.Elem()
	}
	switch v.Kind() {
	case reflect.Bool:
		return v.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int()
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return v.Uint()
	case reflect.Float32, reflect.Float64:
		return v.Float()
	case reflect.String:
		return v.String()
	default:
		return formatValue(v)
	}
}

func setReflectValue(target reflect.Value, value any) ua.StatusCode {
	if !target.IsValid() {
		return ua.BadNodeIDUnknown
	}
	for target.Kind() == reflect.Pointer {
		if target.IsNil() {
			target.Set(reflect.New(target.Type().Elem()))
		}
		target = target.Elem()
	}
	if !target.CanSet() && target.CanAddr() {
		target = reflect.NewAt(target.Type(), unsafe.Pointer(target.UnsafeAddr())).Elem()
	}
	if !target.CanSet() {
		return ua.BadNotWritable
	}
	if value == nil {
		return ua.BadTypeMismatch
	}
	source := reflect.ValueOf(value)
	switch target.Kind() {
	case reflect.Bool:
		v, ok := value.(bool)
		if !ok {
			return ua.BadTypeMismatch
		}
		target.SetBool(v)
		return ua.Good
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v, status := coerceReflectInt64(value)
		if status.IsBad() {
			return status
		}
		if target.OverflowInt(v) {
			return ua.BadOutOfRange
		}
		target.SetInt(v)
		return ua.Good
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v, status := coerceReflectUint64(value)
		if status.IsBad() {
			return status
		}
		if target.OverflowUint(v) {
			return ua.BadOutOfRange
		}
		target.SetUint(v)
		return ua.Good
	case reflect.Float32, reflect.Float64:
		v, status := coerceReflectFloat64(value)
		if status.IsBad() {
			return status
		}
		if target.OverflowFloat(v) {
			return ua.BadOutOfRange
		}
		target.SetFloat(v)
		return ua.Good
	case reflect.String:
		v, ok := value.(string)
		if !ok {
			return ua.BadTypeMismatch
		}
		target.SetString(v)
		return ua.Good
	default:
		if source.IsValid() && source.Type().AssignableTo(target.Type()) {
			target.Set(source)
			return ua.Good
		}
		if source.IsValid() && source.Type().ConvertibleTo(target.Type()) {
			target.Set(source.Convert(target.Type()))
			return ua.Good
		}
		return ua.BadTypeMismatch
	}
}

func coerceReflectInt64(value any) (int64, ua.StatusCode) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return 0, ua.BadTypeMismatch
	}
	switch rv.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return rv.Int(), ua.Good
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v := rv.Uint()
		if v > math.MaxInt64 {
			return 0, ua.BadOutOfRange
		}
		return int64(v), ua.Good
	case reflect.Float32, reflect.Float64:
		v := rv.Float()
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return 0, ua.BadTypeMismatch
		}
		if math.Trunc(v) != v {
			return 0, ua.BadTypeMismatch
		}
		if v < math.MinInt64 || v > math.MaxInt64 {
			return 0, ua.BadOutOfRange
		}
		return int64(v), ua.Good
	default:
		return 0, ua.BadTypeMismatch
	}
}

func coerceReflectUint64(value any) (uint64, ua.StatusCode) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return 0, ua.BadTypeMismatch
	}
	switch rv.Kind() {
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return rv.Uint(), ua.Good
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v := rv.Int()
		if v < 0 {
			return 0, ua.BadOutOfRange
		}
		return uint64(v), ua.Good
	case reflect.Float32, reflect.Float64:
		v := rv.Float()
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return 0, ua.BadTypeMismatch
		}
		if math.Trunc(v) != v {
			return 0, ua.BadTypeMismatch
		}
		if v < 0 || v > math.MaxUint64 {
			return 0, ua.BadOutOfRange
		}
		return uint64(v), ua.Good
	default:
		return 0, ua.BadTypeMismatch
	}
}

func coerceReflectFloat64(value any) (float64, ua.StatusCode) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return 0, ua.BadTypeMismatch
	}
	switch rv.Kind() {
	case reflect.Float32, reflect.Float64:
		v := rv.Float()
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return 0, ua.BadTypeMismatch
		}
		return v, ua.Good
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return float64(rv.Int()), ua.Good
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return float64(rv.Uint()), ua.Good
	default:
		return 0, ua.BadTypeMismatch
	}
}

type tickMsg time.Time

func tickCmd() tea.Cmd {
	return tea.Tick(100*time.Millisecond, func(t time.Time) tea.Msg { return tickMsg(t) })
}

type model struct {
	snapshot *sharedMemory
	tags     []memoryTag
	values   []string
	filtered []int

	query      string
	searchMode bool
	cursor     int
	offset     int
	width      int
	height     int

	lastCycleNS     int64
	longestCycleNS  int64
	shortestCycleNS int64
	avgCycleNS      int64
}

func newModel(snapshot *sharedMemory, tags []memoryTag) model {
	m := model{
		snapshot: snapshot,
		tags:     tags,
		values:   make([]string, len(tags)),
		width:    100,
		height:   28,
	}
	m.applyFilter()
	m.refresh()
	return m
}

func (m model) Init() tea.Cmd {
	return tickCmd()
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tickMsg:
		m.refresh()
		return m, tickCmd()
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
		return m, nil
	case tea.KeyMsg:
		switch msg.String() {
		case "ctrl+c", "q":
			return m, tea.Quit
		case "/":
			m.searchMode = true
			return m, nil
		case "esc":
			m.searchMode = false
			return m, nil
		case "enter":
			if m.searchMode {
				m.searchMode = false
				return m, nil
			}
		case "backspace", "ctrl+h":
			if m.searchMode && len(m.query) > 0 {
				m.query = m.query[:len(m.query)-1]
				m.applyFilter()
			}
			return m, nil
		case "up", "k":
			m.moveCursor(-1)
			return m, nil
		case "down", "j":
			m.moveCursor(1)
			return m, nil
		case "pgup":
			m.moveCursor(-m.visibleRows())
			return m, nil
		case "pgdown":
			m.moveCursor(m.visibleRows())
			return m, nil
		case "home":
			m.cursor = 0
			m.clampWindow()
			return m, nil
		case "end":
			if n := len(m.filtered); n > 0 {
				m.cursor = n - 1
			}
			m.clampWindow()
			return m, nil
		}

		if m.searchMode && len(msg.Runes) > 0 {
			m.query += string(msg.Runes)
			m.applyFilter()
		}
		return m, nil
	}
	return m, nil
}

func (m *model) refresh() {
	m.lastCycleNS, m.longestCycleNS, m.shortestCycleNS, m.avgCycleNS = readCycleStats()
	if m.snapshot == nil {
		return
	}
	m.refreshValues(m.snapshot.Snapshot())
}

func (m *model) refreshValues(mem plcruntime.Memory) {
	rv := reflect.ValueOf(mem)
	for i, tag := range m.tags {
		if len(tag.Index) == 0 {
			m.values[i] = ""
			continue
		}
		m.values[i] = formatValue(rv.FieldByIndex(tag.Index))
	}
}

func (m *model) applyFilter() {
	needle := strings.ToLower(strings.TrimSpace(m.query))
	m.filtered = m.filtered[:0]
	for i, tag := range m.tags {
		if needle == "" || strings.Contains(strings.ToLower(tag.Name), needle) {
			m.filtered = append(m.filtered, i)
		}
	}
	if m.cursor >= len(m.filtered) {
		m.cursor = maxInt(len(m.filtered)-1, 0)
	}
	m.clampWindow()
}

func (m *model) moveCursor(delta int) {
	if len(m.filtered) == 0 {
		m.cursor = 0
		m.offset = 0
		return
	}
	m.cursor += delta
	if m.cursor < 0 {
		m.cursor = 0
	}
	if m.cursor >= len(m.filtered) {
		m.cursor = len(m.filtered) - 1
	}
	m.clampWindow()
}

func (m *model) clampWindow() {
	rows := m.visibleRows()
	if rows <= 0 {
		rows = 1
	}
	if m.offset > m.cursor {
		m.offset = m.cursor
	}
	if m.cursor >= m.offset+rows {
		m.offset = m.cursor - rows + 1
	}
	maxOffset := maxInt(len(m.filtered)-rows, 0)
	if m.offset > maxOffset {
		m.offset = maxOffset
	}
	if m.offset < 0 {
		m.offset = 0
	}
}

func (m model) visibleRows() int {
	rows := m.height - 10
	if rows < 6 {
		rows = 6
	}
	return rows
}

func (m model) View() string {
	headerTitle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("229")).Render("PLC Runtime")
	headerBody := fmt.Sprintf("Cycle(ms) avg=%s last=%s longest=%s shortest=%s", formatCycleMS(m.avgCycleNS), formatCycleMS(m.lastCycleNS), formatCycleMS(m.longestCycleNS), formatCycleMS(m.shortestCycleNS))
	header := lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).Padding(0, 1).Render(headerTitle + "\n" + headerBody)

	searchPrefix := "search"
	if m.searchMode {
		searchPrefix = "search*"
	}
	searchLine := fmt.Sprintf("%s: %s", searchPrefix, m.query)
	metaLine := fmt.Sprintf("tags: %d/%d", len(m.filtered), len(m.tags))

	rows := make([]string, 0, m.visibleRows())
	start := m.offset
	end := minInt(len(m.filtered), start+m.visibleRows())
	for i := start; i < end; i++ {
		idx := m.filtered[i]
		cursor := "  "
		if i == m.cursor {
			cursor = "> "
		}
		row := fmt.Sprintf("%s%s = %s", cursor, m.tags[idx].Name, m.values[idx])
		if i == m.cursor {
			row = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("81")).Render(row)
		}
		rows = append(rows, row)
	}
	if len(rows) == 0 {
		rows = append(rows, "(no tags match current search)")
	}
	list := lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).Padding(0, 1).Render(
		"Memory Tags\n" + searchLine + "\n" + metaLine + "\n\n" + strings.Join(rows, "\n"),
	)

	help := lipgloss.NewStyle().Faint(true).Render("/ search  arrows move  q quit")
	return lipgloss.JoinVertical(lipgloss.Left, header, list, help)
}

func buildMemoryTagIndex(t reflect.Type) []memoryTag {
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct {
		return nil
	}

	tags := make([]memoryTag, 0, t.NumField())
	var walk func(prefix string, st reflect.Type, path []int)
	walk = func(prefix string, st reflect.Type, path []int) {
		for i := 0; i < st.NumField(); i++ {
			field := st.Field(i)
			if strings.HasPrefix(field.Name, "SCLH_") || strings.HasPrefix(field.Name, "__scl") {
				continue
			}
			name := field.Name
			if prefix != "" {
				name = prefix + "." + field.Name
			}
			nextPath := append(append([]int(nil), path...), i)
			ft := field.Type
			if ft.Kind() == reflect.Struct && ft.NumField() > 0 {
				walk(name, ft, nextPath)
				continue
			}
			tags = append(tags, memoryTag{Name: name, Index: nextPath})
		}
	}
	walk("", t, nil)

	sort.Slice(tags, func(i, j int) bool {
		return strings.ToUpper(tags[i].Name) < strings.ToUpper(tags[j].Name)
	})
	return tags
}

func formatValue(v reflect.Value) string {
	if !v.IsValid() {
		return "<invalid>"
	}
	if v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return "<nil>"
		}
		return formatValue(v.Elem())
	}
	if v.CanInterface() {
		return fmt.Sprintf("%v", v.Interface())
	}
	switch v.Kind() {
	case reflect.Bool:
		return fmt.Sprintf("%t", v.Bool())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return fmt.Sprintf("%d", v.Int())
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return fmt.Sprintf("%d", v.Uint())
	case reflect.Float32, reflect.Float64:
		return fmt.Sprintf("%g", v.Float())
	case reflect.String:
		return v.String()
	default:
		return "<unexported>"
	}
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func formatCycleMS(ns int64) string {
	if ns < 0 {
		return "n/a"
	}
	ms := float64(ns) / 1_000_000.0
	if ms < 0.001 {
		return fmt.Sprintf("%.6fms", ms)
	}
	if ms < 1 {
		return fmt.Sprintf("%.3fms", ms)
	}
	if ms < 10 {
		return fmt.Sprintf("%.2fms", ms)
	}
	if ms < 100 {
		return fmt.Sprintf("%.1fms", ms)
	}
	return fmt.Sprintf("%.0fms", ms)
}

func readCycleStats() (last int64, longest int64, shortest int64, avg int64) {
	return 0, 0, -1, -1
}

func runDumpOnce() int {
	var runner plcruntime.Runner
	snapshot := &sharedMemory{}
	runner.Step()
	snapshot.Set(runner.Mem)
	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	m := newModel(snapshot, tags)
	fmt.Println(m.View())
	return 0
}

func runInteractive(opcuaPort int, scanPeriod time.Duration, snapshotPeriod time.Duration) error {
	snapshot := &sharedMemory{}
	state := newRuntimeState(snapshot, snapshotPeriod)
	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))

	opcuaSrv, err := startOPCUAServer(snapshot, tags, nil, opcuaPort)
	if err != nil {
		return err
	}
	if opcuaSrv != nil {
		defer func() {
			_ = opcuaSrv.Close()
		}()
	}

	done := make(chan struct{})
	defer close(done)

	go state.run(done, scanPeriod)

	p := tea.NewProgram(newModel(snapshot, tags), tea.WithAltScreen())
	_, err = p.Run()
	return err
}

func runHeadless(cycles int, duration time.Duration) int {
	var runner plcruntime.Runner
	if cycles <= 0 && duration <= 0 {
		return 0
	}
	start := time.Now()
	if cycles > 0 {
		for i := 0; i < cycles; i++ {
			runner.Step()
		}
		elapsed := time.Since(start)
		if elapsed > 0 {
			fmt.Printf("cycles %d, elapsed %s, cps %.0f\n", cycles, elapsed, float64(cycles)/elapsed.Seconds())
		}
		return 0
	}

	deadline := time.Now().Add(duration)
	n := 0
	for {
		runner.Step()
		n++
		if n&255 == 0 {
			if time.Now().After(deadline) {
				break
			}
		}
	}
	elapsed := time.Since(start)
	if elapsed > 0 {
		fmt.Printf("cycles %d, elapsed %s, cps %.0f\n", n, elapsed, float64(n)/elapsed.Seconds())
	}
	return 0
}

func main() {
	dumpOnce := flag.Bool("dump-once", false, "run one scan, print one TUI frame, and exit")
	opcuaPort := flag.Int("opcua-port", 4840, "OPC-UA server port (set 0 to disable)")
	scanPeriod := flag.Duration("scan-period", 0, "delay between scan cycles (0 to run as fast as possible)")
	snapshotPeriod := flag.Duration("snapshot-period", 20*time.Millisecond, "how often to snapshot runtime memory for the TUI/OPC-UA (0 to snapshot every scan)")
	cycles := flag.Int("cycles", 0, "run N scan cycles headless and exit")
	duration := flag.Duration("duration", 0, "run headless for duration and exit")
	symbolMapPath := flag.String("symbol-map", "symbol_map.json", "path to generated symbol_map.json")
	flag.Parse()

	if *dumpOnce {
		os.Exit(runDumpOnce())
	}
	if *cycles > 0 || *duration > 0 {
		os.Exit(runHeadless(*cycles, *duration))
	}
	if stdinHasDebugProtocolInput() {
		if err := runProtocol(*symbolMapPath, *opcuaPort, *scanPeriod, *snapshotPeriod); err != nil {
			fmt.Fprintln(os.Stderr, "plc-run:", err)
			os.Exit(1)
		}
		return
	}

	if err := runInteractive(*opcuaPort, *scanPeriod, *snapshotPeriod); err != nil {
		fmt.Fprintln(os.Stderr, "plc-run:", err)
		os.Exit(1)
	}
}
