// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"github.com/awcullen/opcua/ua"
	"os"
	"plc-autogen/runtime"
	"reflect"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"
)

const entryGeneratedSymbol = "OB1"
const entryKindSymbol = "ORGANIZATION_BLOCK"
const entryFallbackFrameName = "OB1"
const runtimeHasDebugSnapshots = false

type runtimeFrame struct {
	Name   string `json:"name,omitempty"`
	Path   string `json:"path,omitempty"`
	Line   int    `json:"line,omitempty"`
	Column int    `json:"column,omitempty"`
}

type runtimeMetrics struct {
	HeapAllocBytes  uint64 `json:"heapAllocBytes,omitempty"`
	HeapInuseBytes  uint64 `json:"heapInuseBytes,omitempty"`
	SysBytes        uint64 `json:"sysBytes,omitempty"`
	NumGC           uint32 `json:"numGc,omitempty"`
	LastCycleNS     int64  `json:"lastCycleNs,omitempty"`
	AverageCycleNS  int64  `json:"averageCycleNs,omitempty"`
	ShortestCycleNS int64  `json:"shortestCycleNs,omitempty"`
	LongestCycleNS  int64  `json:"longestCycleNs,omitempty"`
}

type runtimeRequest struct {
	ID     int             `json:"id"`
	Method string          `json:"method"`
	Params json.RawMessage `json:"params,omitempty"`
}

type runtimeResponse struct {
	ID     int    `json:"id"`
	Result any    `json:"result,omitempty"`
	Error  string `json:"error,omitempty"`
}

type runtimeEvent struct {
	Event  string `json:"event"`
	Params any    `json:"params,omitempty"`
}

type symbolEntry struct {
	Original  string `json:"original"`
	Generated string `json:"generated"`
	Kind      string `json:"kind,omitempty"`
	Path      string `json:"path,omitempty"`
	Line      int    `json:"line,omitempty"`
	Column    int    `json:"column,omitempty"`
}

type symbolMapFile struct {
	Entries            []symbolEntry            `json:"entries"`
	StatementVariables []statementVariableEntry `json:"statement_variables,omitempty"`
}

type statementVariableRef struct {
	Name    string `json:"name"`
	IsWrite bool   `json:"is_write,omitempty"`
}

type statementVariableEntry struct {
	DebugID   string                 `json:"debug_id"`
	Block     string                 `json:"block,omitempty"`
	Path      string                 `json:"path,omitempty"`
	Line      int                    `json:"line,omitempty"`
	Column    int                    `json:"column,omitempty"`
	Variables []statementVariableRef `json:"variables,omitempty"`
}

type runtimeState struct {
	mu              sync.RWMutex
	runner          plcruntime.Runner
	snapshot        *sharedMemory
	snapshotPeriod  time.Duration
	nextSnapshot    time.Time
	cycles          int64
	totalCycleNS    int64
	lastCycleNS     int64
	shortestCycleNS int64
	longestCycleNS  int64
}

type debugSnapshotStore struct {
	mu         sync.RWMutex
	activeID   string
	statements []statementVariableEntry
	values     map[string]map[string]DebugSnapshotVariable
}

func newDebugSnapshotStore(entries []statementVariableEntry) *debugSnapshotStore {
	if len(entries) == 0 {
		return nil
	}
	statements := make([]statementVariableEntry, 0, len(entries))
	for _, entry := range entries {
		id := strings.TrimSpace(entry.DebugID)
		if id == "" {
			continue
		}
		copied := statementVariableEntry{DebugID: id, Block: entry.Block, Path: entry.Path, Line: entry.Line, Column: entry.Column}
		if len(entry.Variables) > 0 {
			copied.Variables = make([]statementVariableRef, 0, len(entry.Variables))
			seen := map[string]struct{}{}
			for _, ref := range entry.Variables {
				name := strings.TrimSpace(ref.Name)
				if name == "" {
					continue
				}
				key := strings.ToUpper(name)
				if _, ok := seen[key]; ok {
					continue
				}
				seen[key] = struct{}{}
				copied.Variables = append(copied.Variables, statementVariableRef{Name: name, IsWrite: ref.IsWrite})
			}
		}
		statements = append(statements, copied)
	}
	if len(statements) == 0 {
		return nil
	}
	return &debugSnapshotStore{statements: statements, values: map[string]map[string]DebugSnapshotVariable{}}
}

func (s *debugSnapshotStore) Update(id string, vars []DebugSnapshotVariable) {
	if s == nil {
		return
	}
	id = strings.TrimSpace(id)
	if id == "" {
		return
	}
	byName := make(map[string]DebugSnapshotVariable, len(vars))
	for _, variable := range vars {
		name := strings.TrimSpace(variable.Name)
		if name == "" {
			continue
		}
		copied := variable
		copied.Name = name
		byName[strings.ToUpper(name)] = copied
	}
	s.mu.Lock()
	s.activeID = id
	s.values[id] = byName
	s.mu.Unlock()
}

func (s *debugSnapshotStore) ReadValue(debugID string, name string) any {
	if s == nil {
		return ""
	}
	debugID = strings.TrimSpace(debugID)
	name = strings.TrimSpace(name)
	if debugID == "" || name == "" {
		return ""
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	if s.activeID != debugID {
		return ""
	}
	entry := s.values[debugID]
	if entry == nil {
		return ""
	}
	variable, ok := entry[strings.ToUpper(name)]
	if !ok {
		return ""
	}
	if variable.Value == nil {
		return ""
	}
	return variable.Value
}

func (s *debugSnapshotStore) Snapshot(debugID string) []DebugSnapshotVariable {
	if s == nil {
		return nil
	}
	debugID = strings.TrimSpace(debugID)
	if debugID == "" {
		return nil
	}
	s.mu.RLock()
	entry := s.values[debugID]
	s.mu.RUnlock()
	if entry == nil {
		return nil
	}
	out := make([]DebugSnapshotVariable, 0, len(entry))
	for _, variable := range entry {
		out = append(out, variable)
	}
	return out
}

func (s *debugSnapshotStore) Statements() []statementVariableEntry {
	if s == nil {
		return nil
	}
	out := make([]statementVariableEntry, len(s.statements))
	copy(out, s.statements)
	return out
}

func newRuntimeState(snapshot *sharedMemory, snapshotPeriod time.Duration) *runtimeState {
	s := &runtimeState{snapshot: snapshot, snapshotPeriod: snapshotPeriod}
	if snapshot != nil {
		snapshot.AttachRuntime(s)
		snapshot.Set(s.runner.Mem)
	}
	SetDebugPauseHooks(func() {
		s.mu.Unlock()
	}, func() {
		s.mu.Lock()
	})
	return s
}

func (s *runtimeState) MemorySnapshot() plcruntime.Memory {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.runner.Mem
}

func (s *runtimeState) WriteMemoryValue(index []int, value any) ua.StatusCode {
	if len(index) == 0 {
		return ua.BadNodeIDUnknown
	}
	// Synchronize every OPC write through runtimeState.mu, including paused sessions.
	// Debug pause hooks release and reacquire the same mutex around the blocked scan step,
	// so paused OPC reads, writes, and scan-step memory ownership all follow one lock discipline.
	s.mu.Lock()
	defer s.mu.Unlock()
	target := reflect.ValueOf(&s.runner.Mem).Elem().FieldByIndex(index)
	return setReflectValue(target, value)
}

func (s *runtimeState) Step() {
	s.mu.Lock()
	startedAt := time.Now()
	s.runner.Step()
	cycleNS := time.Since(startedAt).Nanoseconds()
	if cycleNS <= 0 {
		cycleNS = 1
	}
	s.cycles++
	s.totalCycleNS += cycleNS
	s.lastCycleNS = cycleNS
	if s.shortestCycleNS == 0 || cycleNS < s.shortestCycleNS {
		s.shortestCycleNS = cycleNS
	}
	if cycleNS > s.longestCycleNS {
		s.longestCycleNS = cycleNS
	}
	if s.snapshot != nil {
		if s.snapshotPeriod <= 0 {
			s.snapshot.Set(s.runner.Mem)
		} else {
			now := time.Now()
			if s.nextSnapshot.IsZero() || !now.Before(s.nextSnapshot) {
				s.snapshot.Set(s.runner.Mem)
				s.nextSnapshot = now.Add(s.snapshotPeriod)
			}
		}
	}
	s.mu.Unlock()
}

func (s *runtimeState) Cycles() int64 {
	if DebugIsPaused() {
		return s.cycles
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.cycles
}

func (s *runtimeState) Running() bool {
	return !DebugIsPaused()
}

func (s *runtimeState) Metrics() runtimeMetrics {
	if DebugIsPaused() {
		return s.metricsSnapshot()
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.metricsSnapshot()
}

func (s *runtimeState) metricsSnapshot() runtimeMetrics {
	cycles := s.cycles
	lastCycleNS := s.lastCycleNS
	shortestCycleNS := s.shortestCycleNS
	longestCycleNS := s.longestCycleNS
	totalCycleNS := s.totalCycleNS

	averageCycleNS := int64(0)
	if cycles > 0 {
		averageCycleNS = totalCycleNS / cycles
	}
	var memoryStats runtime.MemStats
	runtime.ReadMemStats(&memoryStats)
	return runtimeMetrics{
		HeapAllocBytes:  memoryStats.HeapAlloc,
		HeapInuseBytes:  memoryStats.HeapInuse,
		SysBytes:        memoryStats.Sys,
		NumGC:           memoryStats.NumGC,
		LastCycleNS:     lastCycleNS,
		AverageCycleNS:  averageCycleNS,
		ShortestCycleNS: shortestCycleNS,
		LongestCycleNS:  longestCycleNS,
	}
}

func (s *runtimeState) run(done <-chan struct{}, scanPeriod time.Duration) {
	step := func() bool {
		select {
		case <-done:
			return false
		default:
		}
		s.Step()
		return true
	}
	if scanPeriod <= 0 {
		for step() {
		}
		return
	}
	ticker := time.NewTicker(scanPeriod)
	defer ticker.Stop()
	for {
		select {
		case <-done:
			return
		case <-ticker.C:
			if !step() {
				return
			}
		}
	}
}

func loadSymbolData(path string) symbolMapFile {
	data, err := os.ReadFile(path)
	if err != nil {
		return symbolMapFile{}
	}
	var payload symbolMapFile
	if err := json.Unmarshal(data, &payload); err != nil {
		return symbolMapFile{}
	}
	return payload
}

func findEntryFrame(entries []symbolEntry, generatedName string, entryKind string, fallbackName string) runtimeFrame {
	if strings.TrimSpace(fallbackName) == "" {
		fallbackName = "PLC Cycle"
	}
	out := runtimeFrame{Name: fallbackName, Line: 1, Column: 1}
	for _, e := range entries {
		if !strings.EqualFold(strings.TrimSpace(e.Generated), strings.TrimSpace(generatedName)) {
			continue
		}
		if strings.TrimSpace(entryKind) != "" && !strings.EqualFold(strings.TrimSpace(e.Kind), strings.TrimSpace(entryKind)) {
			continue
		}
		if name := strings.TrimSpace(e.Original); name != "" {
			out.Name = name
		}
		if path := strings.TrimSpace(e.Path); path != "" {
			out.Path = path
		}
		if e.Line > 0 {
			out.Line = e.Line
		}
		if e.Column > 0 {
			out.Column = e.Column
		}
		return out
	}
	return out
}

func debugLocationFromID(id string) (block string, sourcePath string, line int, ok bool) {
	id = strings.TrimSpace(id)
	if id == "" {
		return "", "", 0, false
	}
	dot := strings.Index(id, ".")
	colon := strings.LastIndex(id, ":")
	if dot <= 0 || colon <= dot+1 || colon >= len(id)-1 {
		return "", "", 0, false
	}
	block = strings.TrimSpace(id[:dot])
	sourcePath = strings.TrimSpace(id[dot+1 : colon])
	parsedLine, err := strconv.Atoi(strings.TrimSpace(id[colon+1:]))
	if err != nil || parsedLine <= 0 {
		return "", "", 0, false
	}
	return block, sourcePath, parsedLine, true
}

func normalizePausedFrame(frame runtimeFrame, pause DebugPauseState) runtimeFrame {
	block, sourcePath, line, ok := debugLocationFromID(pause.ID)
	if !ok {
		return frame
	}
	if name := strings.TrimSpace(frame.Name); name != "" && block != "" && !strings.EqualFold(name, block) {
		return frame
	}
	if block != "" {
		frame.Name = block
	}
	if sourcePath != "" {
		frame.Path = sourcePath
	}
	if line > 0 {
		frame.Line = line
	}
	if frame.Column <= 0 {
		frame.Column = 1
	}
	return frame
}

func currentCallStack(entryFrame runtimeFrame, pause DebugPauseState) []runtimeFrame {
	stack := GetStack()
	out := make([]runtimeFrame, 0, len(stack)+1)
	for i := len(stack) - 1; i >= 0; i-- {
		frame := stack[i]
		name := strings.TrimSpace(frame.BlockName)
		if name == "" {
			name = entryFrame.Name
		}
		out = append(out, runtimeFrame{Name: name, Path: strings.TrimSpace(frame.SourceFile), Line: frame.SourceLine, Column: 1})
	}
	callerFrame := entryFrame
	if len(out) > 0 {
		if sourcePath := strings.TrimSpace(out[0].Path); sourcePath != "" {
			callerFrame.Path = sourcePath
		}
		if out[0].Line > 0 {
			callerFrame.Line = out[0].Line
		}
		if out[0].Column > 0 {
			callerFrame.Column = out[0].Column
		}
	}
	if len(out) == 0 {
		out = append(out, entryFrame)
	} else {
		out = append(out, callerFrame)
	}
	if len(out) > 0 && strings.TrimSpace(pause.ID) != "" {
		out[0] = normalizePausedFrame(out[0], pause)
	}
	return out
}

func currentFrame(entryFrame runtimeFrame, pause DebugPauseState) runtimeFrame {
	stack := currentCallStack(entryFrame, pause)
	if len(stack) == 0 {
		return entryFrame
	}
	return stack[0]
}

func runtimeStatePayload(state *runtimeState, entryFrame runtimeFrame) map[string]any {
	pause := CurrentDebugPauseState()
	return map[string]any{
		"cycles":    state.Cycles(),
		"running":   state.Running(),
		"frame":     currentFrame(entryFrame, pause),
		"callStack": currentCallStack(entryFrame, pause),
		"metrics":   state.Metrics(),
	}
}

func stoppedEventPayload(state *runtimeState, entryFrame runtimeFrame, pause DebugPauseState) map[string]any {
	payload := runtimeStatePayload(state, entryFrame)
	payload["reason"] = pause.Reason
	payload["id"] = pause.ID
	return payload
}

func buildMemoryTagLookup(tags []memoryTag) map[string][]int {
	out := make(map[string][]int, len(tags))
	for _, tag := range tags {
		name := strings.TrimSpace(tag.Name)
		if name == "" {
			continue
		}
		out[strings.ToUpper(name)] = append([]int(nil), tag.Index...)
	}
	return out
}

func memoryLeafType(index []int) (reflect.Type, bool) {
	t := reflect.TypeOf(plcruntime.Memory{})
	for _, i := range index {
		for t.Kind() == reflect.Ptr {
			t = t.Elem()
		}
		if t.Kind() != reflect.Struct {
			return nil, false
		}
		if i < 0 || i >= t.NumField() {
			return nil, false
		}
		field := t.Field(i)
		t = field.Type
	}
	return t, true
}

func memoryLeafKind(index []int) (reflect.Kind, bool) {
	leaf, ok := memoryLeafType(index)
	if !ok || leaf == nil {
		return reflect.Invalid, false
	}
	for leaf.Kind() == reflect.Ptr {
		leaf = leaf.Elem()
	}
	return leaf.Kind(), true
}

func runtimeTypeNameForMemoryIndex(index []int) string {
	leaf, ok := memoryLeafType(index)
	if !ok || leaf == nil {
		return ""
	}
	for leaf.Kind() == reflect.Ptr {
		leaf = leaf.Elem()
	}
	switch leaf.Kind() {
	case reflect.Bool:
		return "bool"
	case reflect.Int:
		return "int"
	case reflect.Int8:
		return "int8"
	case reflect.Int16:
		return "int16"
	case reflect.Int32:
		return "int32"
	case reflect.Int64:
		return "int64"
	case reflect.Uint:
		return "uint"
	case reflect.Uint8:
		return "uint8"
	case reflect.Uint16:
		return "uint16"
	case reflect.Uint32:
		return "uint32"
	case reflect.Uint64:
		return "uint64"
	case reflect.Float32:
		return "float32"
	case reflect.Float64:
		return "float64"
	case reflect.String:
		return "string"
	default:
		return leaf.Kind().String()
	}
}

func memoryIndexIsInteger(index []int) bool {
	kind, ok := memoryLeafKind(index)
	if !ok {
		return false
	}
	switch kind {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return true
	default:
		return false
	}
}

func handleRuntimeRequest(req runtimeRequest, state *runtimeState, entryFrame runtimeFrame, snapshot *sharedMemory, tagLookup map[string][]int, debugSnapshots *debugSnapshotStore) runtimeResponse {
	resp := runtimeResponse{ID: req.ID}
	switch req.Method {
	case "getMemoryValues":
		var args struct {
			Tags []string `json:"tags"`
		}
		_ = json.Unmarshal(req.Params, &args)
		values := make([]any, len(args.Tags))
		types := make([]string, len(args.Tags))
		for i, tag := range args.Tags {
			key := strings.ToUpper(strings.TrimSpace(tag))
			if key == "" {
				continue
			}
			idx, ok := tagLookup[key]
			if !ok {
				continue
			}
			values[i] = readOPCUATagValue(snapshot, idx)
			types[i] = runtimeTypeNameForMemoryIndex(idx)
		}
		resp.Result = map[string]any{"values": values, "types": types}
	case "setMemoryValue":
		var args struct {
			Tag   string `json:"tag"`
			Value any    `json:"value"`
		}
		_ = json.Unmarshal(req.Params, &args)
		key := strings.ToUpper(strings.TrimSpace(args.Tag))
		if key == "" {
			resp.Error = "missing tag name"
			break
		}
		idx, ok := tagLookup[key]
		if !ok {
			resp.Error = fmt.Sprintf("unknown tag: %s", args.Tag)
			break
		}
		if n, ok := args.Value.(float64); ok {
			if memoryIndexIsInteger(idx) && n != float64(int64(n)) {
				resp.Error = fmt.Sprintf("invalid integer value for %s: %v", args.Tag, n)
				break
			}
		}
		written, status := snapshot.Write(idx, args.Value)
		if status.IsBad() {
			resp.Error = fmt.Sprintf("write failed: %s", status)
			break
		}
		resp.Result = map[string]any{"ok": true, "value": written}
	case "setBreakpoint":
		var args struct {
			ID string `json:"id"`
		}
		_ = json.Unmarshal(req.Params, &args)
		if strings.TrimSpace(args.ID) == "" {
			resp.Error = "missing breakpoint id"
			break
		}
		SetBreakpoint(args.ID)
		resp.Result = map[string]any{"ok": true}
	case "clearBreakpoint":
		var args struct {
			ID string `json:"id"`
		}
		_ = json.Unmarshal(req.Params, &args)
		if strings.TrimSpace(args.ID) == "" {
			resp.Error = "missing breakpoint id"
			break
		}
		ClearBreakpoint(args.ID)
		resp.Result = map[string]any{"ok": true}
	case "stepNext":
		StepNext()
		resp.Result = map[string]any{"running": true}
	case "stepInto":
		StepInto()
		resp.Result = map[string]any{"running": true}
	case "stepOut":
		StepOut()
		resp.Result = map[string]any{"running": true}
	case "continue":
		Continue()
		resp.Result = map[string]any{"running": true}
	case "pause":
		Pause()
		resp.Result = map[string]any{"requested": true}
	case "getState":
		resp.Result = runtimeStatePayload(state, entryFrame)
	case "getDebugSnapshots":
		var args struct {
			IDs []string
		}
		_ = json.Unmarshal(req.Params, &args)
		out := map[string]any{}
		if debugSnapshots != nil {
			for _, rawID := range args.IDs {
				id := strings.TrimSpace(rawID)
				if id == "" {
					continue
				}
				vars := debugSnapshots.Snapshot(id)
				if len(vars) == 0 {
					continue
				}
				out[id] = vars
			}
		}
		resp.Result = map[string]any{"snapshots": out}
	default:
		resp.Error = fmt.Sprintf("unknown method: %s", req.Method)
	}
	return resp
}

func stdinHasDebugProtocolInput() bool {
	info, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice == 0
}

type jsonLineWriter struct {
	mu  sync.Mutex
	enc *json.Encoder
}

func (w *jsonLineWriter) Write(v any) error {
	w.mu.Lock()
	defer w.mu.Unlock()
	return w.enc.Encode(v)
}

func runProtocol(symbolMapPath string, opcuaPort int, scanPeriod time.Duration, snapshotPeriod time.Duration) error {
	symbolData := loadSymbolData(symbolMapPath)
	entryFrame := findEntryFrame(symbolData.Entries, entryGeneratedSymbol, entryKindSymbol, entryFallbackFrameName)
	snapshot := &sharedMemory{}
	state := newRuntimeState(snapshot, snapshotPeriod)
	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	tagLookup := buildMemoryTagLookup(tags)
	debugSnapshots := (*debugSnapshotStore)(nil)
	if runtimeHasDebugSnapshots {
		debugSnapshots = newDebugSnapshotStore(symbolData.StatementVariables)
		SetDebugSnapshotSink(debugSnapshots.Update)
		defer SetDebugSnapshotSink(nil)
	}

	opcuaSrv, err := startOPCUAServer(snapshot, tags, debugSnapshots, opcuaPort)
	if err != nil {
		return err
	}
	if opcuaSrv != nil {
		defer func() { _ = opcuaSrv.Close() }()
	}

	done := make(chan struct{})
	defer close(done)
	go state.run(done, scanPeriod)

	writer := &jsonLineWriter{enc: json.NewEncoder(os.Stdout)}
	go func() {
		ticker := time.NewTicker(20 * time.Millisecond)
		defer ticker.Stop()
		wasPaused := false
		last := DebugPauseState{}
		for {
			select {
			case <-done:
				return
			case <-ticker.C:
			}
			if !(DebugIsPaused()) {
				wasPaused = false
				last = DebugPauseState{}
				continue
			}
			pause := CurrentDebugPauseState()
			if wasPaused && pause == last {
				continue
			}
			wasPaused = true
			last = pause
			_ = writer.Write(runtimeEvent{Event: "stopped", Params: stoppedEventPayload(state, entryFrame, pause)})
		}
	}()

	scanner := bufio.NewScanner(os.Stdin)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		var req runtimeRequest
		if err := json.Unmarshal([]byte(line), &req); err != nil {
			if err := writer.Write(runtimeResponse{ID: 0, Error: "invalid JSON request"}); err != nil {
				return err
			}
			continue
		}
		if err := writer.Write(handleRuntimeRequest(req, state, entryFrame, snapshot, tagLookup, debugSnapshots)); err != nil {
			return err
		}
	}
	if err := scanner.Err(); err != nil {
		return err
	}
	return nil
}
