// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package builtins

func trapBuiltinStub(name string) {
	// Note: keep this allocation-free. The panic message is fully constant at each call site.
	panic(name)
}
