// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package builtins

import (
	"reflect"
	"sync/atomic"
)

type builtinSigned interface {
	~int | ~int8 | ~int16 | ~int32 | ~int64
}

type builtinUnsigned interface {
	~uint | ~uint8 | ~uint16 | ~uint32 | ~uint64 | ~uintptr
}

type builtinInteger interface {
	builtinSigned | builtinUnsigned
}

type builtinFloat interface {
	~float32 | ~float64
}

type builtinNumber interface {
	builtinInteger | builtinFloat
}

type builtinAbsNumber interface {
	builtinSigned | builtinFloat
}

// --- Runtime stats shared by builtins ---

// lastCycleNS is updated by the generated runtime once per scan step.
// Values are nanoseconds.
var lastCycleNS int64
var longestCycleNS int64
var shortestCycleNS int64 = -1

// cycleWindow* are rolling aggregates used for UI reporting.
// They are reset by the UI reader.
var cycleWindowNS int64
var cycleWindowCount int64

func SetLastCycleNS(ns int64) {
	atomic.AddInt64(&cycleWindowNS, ns)
	atomic.AddInt64(&cycleWindowCount, 1)
	atomic.StoreInt64(&lastCycleNS, ns)
	for {
		cur := atomic.LoadInt64(&longestCycleNS)
		if ns <= cur {
			break
		}
		if atomic.CompareAndSwapInt64(&longestCycleNS, cur, ns) {
			break
		}
	}
	for {
		cur := atomic.LoadInt64(&shortestCycleNS)
		if cur >= 0 && ns >= cur {
			break
		}
		if atomic.CompareAndSwapInt64(&shortestCycleNS, cur, ns) {
			break
		}
	}
}

func GetLastCycleNS() int64 {
	return atomic.LoadInt64(&lastCycleNS)
}

func GetLongestCycleNS() int64 {
	return atomic.LoadInt64(&longestCycleNS)
}

func GetShortestCycleNS() int64 {
	return atomic.LoadInt64(&shortestCycleNS)
}

func GetAndResetCycleWindow() (sumNS int64, count int64) {
	// Order is not important; reader uses best-effort window.
	sumNS = atomic.SwapInt64(&cycleWindowNS, 0)
	count = atomic.SwapInt64(&cycleWindowCount, 0)
	return sumNS, count
}

func ptrKey(p any) uintptr {
	rv := reflect.ValueOf(p)
	if !rv.IsValid() || rv.Kind() != reflect.Ptr || rv.IsNil() {
		return 0
	}
	return rv.Pointer()
}

func structField(inst any, name string) (reflect.Value, bool) {
	rv := reflect.ValueOf(inst)
	if !rv.IsValid() || rv.Kind() != reflect.Ptr || rv.IsNil() {
		return reflect.Value{}, false
	}
	ev := rv.Elem()
	if ev.Kind() != reflect.Struct {
		return reflect.Value{}, false
	}
	fv := ev.FieldByName(name)
	if !fv.IsValid() {
		return reflect.Value{}, false
	}
	return fv, true
}

func getStructFieldBool(inst any, name string) (bool, bool) {
	fv, ok := structField(inst, name)
	if !ok || fv.Kind() != reflect.Bool {
		return false, false
	}
	return fv.Bool(), true
}

func getStructFieldInt64Like(inst any, name string) (int64, bool) {
	fv, ok := structField(inst, name)
	if !ok {
		return 0, false
	}
	switch fv.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return fv.Int(), true
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return int64(fv.Uint()), true
	default:
		return 0, false
	}
}

func setStructFieldBool(inst any, name string, v bool) {
	fv, ok := structField(inst, name)
	if !ok || !fv.CanSet() || fv.Kind() != reflect.Bool {
		return
	}
	fv.SetBool(v)
}

func setStructFieldInt64Like(inst any, name string, v int64) {
	fv, ok := structField(inst, name)
	if !ok || !fv.CanSet() {
		return
	}
	switch fv.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		fv.SetInt(v)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		if v < 0 {
			return
		}
		fv.SetUint(uint64(v))
	}
}

func timerInstanceInputs(inst any) (in bool, ptNS int64) {
	if v, ok := getStructFieldBool(inst, "IN"); ok {
		in = v
	}
	if v, ok := getStructFieldInt64Like(inst, "PT"); ok {
		ptNS = v
	}
	return in, ptNS
}

func setTimerInstanceFields(inst any, in bool, ptNS int64, q bool, etNS int64) {
	setStructFieldBool(inst, "IN", in)
	setStructFieldInt64Like(inst, "PT", ptNS)
	setStructFieldBool(inst, "Q", q)
	setStructFieldInt64Like(inst, "ET", etNS)
}

func asBool(v any) (bool, bool) {
	switch x := v.(type) {
	case bool:
		return x, true
	case int:
		return x != 0, true
	case int8:
		return x != 0, true
	case int16:
		return x != 0, true
	case int32:
		return x != 0, true
	case int64:
		return x != 0, true
	case uint:
		return x != 0, true
	case uint8:
		return x != 0, true
	case uint16:
		return x != 0, true
	case uint32:
		return x != 0, true
	case uint64:
		return x != 0, true
	default:
		rv := reflect.ValueOf(v)
		if !rv.IsValid() {
			return false, false
		}
		switch rv.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			return rv.Int() != 0, true
		case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
			return rv.Uint() != 0, true
		default:
			return false, false
		}
	}
}

func asInt64(v any) (int64, bool) {
	switch x := v.(type) {
	case int:
		return int64(x), true
	case int8:
		return int64(x), true
	case int16:
		return int64(x), true
	case int32:
		return int64(x), true
	case int64:
		return x, true
	case uint:
		return int64(x), true
	case uint8:
		return int64(x), true
	case uint16:
		return int64(x), true
	case uint32:
		return int64(x), true
	case uint64:
		return int64(x), true
	default:
		rv := reflect.ValueOf(v)
		if !rv.IsValid() {
			return 0, false
		}
		switch rv.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			return rv.Int(), true
		case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
			return int64(rv.Uint()), true
		default:
			return 0, false
		}
	}
}

func setOutBoolLike(dst any, v bool) {
	rv := reflect.ValueOf(dst)
	if !rv.IsValid() || rv.Kind() != reflect.Ptr || rv.IsNil() {
		return
	}
	ev := rv.Elem()
	if !ev.CanSet() {
		return
	}
	if ev.Kind() == reflect.Bool {
		ev.SetBool(v)
	}
}

func setOutInt64Like(dst any, v int64) {
	rv := reflect.ValueOf(dst)
	if !rv.IsValid() || rv.Kind() != reflect.Ptr || rv.IsNil() {
		return
	}
	ev := rv.Elem()
	if !ev.CanSet() {
		return
	}
	switch ev.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		val := reflect.ValueOf(v)
		if val.Type().ConvertibleTo(ev.Type()) {
			ev.Set(val.Convert(ev.Type()))
		}
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		val := reflect.ValueOf(uint64(v))
		if val.Type().ConvertibleTo(ev.Type()) {
			ev.Set(val.Convert(ev.Type()))
		}
	}
}
