// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_DINT_TO_TIME.scl:4:1
func FC_FC_DINT_TO_TIME(mem *Memory, v_DintValue int32) (ret TIME) {
	_ = ret

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_DINT_TO_TIME.scl:13:5
	ret = TIME(0)
	return
}

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_INT_TO_TIME.scl:4:1
func FC_FC_INT_TO_TIME(mem *Memory, v_IntValue int16) (ret TIME) {
	_ = ret

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_INT_TO_TIME.scl:11:5
	ret = TIME(0)
	return
}

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:14:1
func FC_FC_LogMsg(mem *Memory, v_Enable bool, v_Level int16, v_Source STRING_32, v_Message STRING_128, v_LogBuffer *[32]uint8, v_BufferIndex *int16, v_Status *int16) (ret int16) {
	_ = ret

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:30:5
	if !(v_Enable) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:31:9
		(*v_Status) = int16((0 - 1))
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:32:9
		ret = int16((0 - 1))
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:33:9
		return
	}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:41:5
	(*v_Status) = int16(0)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/log/FC_LogMsg.scl:42:5
	ret = int16(0)
	return
}

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_TIME_TO_DINT.scl:4:1
func FC_FC_TIME_TO_DINT(mem *Memory, v_TimeValue TIME) (ret int32) {
	_ = ret

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_TIME_TO_DINT.scl:12:5
	ret = int32(0)
	return
}

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_TIME_TO_INT.scl:4:1
func FC_FC_TIME_TO_INT(mem *Memory, v_TimeValue TIME) (ret int16) {
	_ = ret

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/01_SharedLibraries/SysLib/convert/FC_TIME_TO_INT.scl:11:5
	ret = int16(0)
	return
}
