// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:31:1
func OB_OB1(mem *Memory) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:37:5
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bEnable = mem.v_GlobalVars.v_stExternal.v_i_bEnable
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bAutoMode = mem.v_GlobalVars.v_stExternal.v_i_bAutoMode
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bManualMode = mem.v_GlobalVars.v_stExternal.v_i_bManualMode
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bStart = mem.v_GlobalVars.v_stExternal.v_i_bStart
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bStop = mem.v_GlobalVars.v_stExternal.v_i_bStop
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bReset = mem.v_GlobalVars.v_stExternal.v_i_bReset
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bFrameMachine_AutoRunning = mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_AutoRunning
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bFrameMachine_AllowFeed = mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_AllowFeed
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bFrameMaterialRequest = mem.v_GlobalVars.v_stExternal.v_i_bFrameMaterialRequest
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bDoorOpenRequest = mem.v_GlobalVars.v_stExternal.v_i_bDoorOpenRequest
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bFrameMachine_EStop = mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_EStop
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bFrameMachine_SafetyErr = mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_SafetyErr
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bFrameMachine_CommErr = mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_CommErr
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bGlueMachine_AutoRunning = mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_AutoRunning
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bGlueMachine_AllowFeed = mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_AllowFeed
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bGlueMachine_PickComplete = mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_PickComplete
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bGlueMachine_Fault = mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_Fault
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bGlueMachine_EStop = mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_EStop
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bGlueMachine_CommErr = mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_CommErr
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bRobot_AutoRunning = mem.v_GlobalVars.v_stExternal.v_i_bRobot_AutoRunning
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bRobot_StackComplete = mem.v_GlobalVars.v_stExternal.v_i_bRobot_StackComplete
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bRobot_Fault = mem.v_GlobalVars.v_stExternal.v_i_bRobot_Fault
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bRobot_EStop = mem.v_GlobalVars.v_stExternal.v_i_bRobot_EStop
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bRobot_CommErr = mem.v_GlobalVars.v_stExternal.v_i_bRobot_CommErr
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bLocalReady = mem.v_GlobalVars.v_stExternal.v_i_bLocalReady
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bAnyAlarmActive = mem.v_GlobalVars.v_stExternal.v_i_bAnyAlarmActive
	mem.v_GlobalVars.v_fbExternalDevice.v_i_bSystemFault = mem.v_GlobalVars.v_stExternal.v_i_bSystemFault
	FB_FB_ExternalDeviceInteraction(mem, &mem.v_GlobalVars.v_fbExternalDevice)
	mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_RequestFeed = mem.v_GlobalVars.v_fbExternalDevice.v_q_bFrameMachine_RequestFeed
	mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_Pause = mem.v_GlobalVars.v_fbExternalDevice.v_q_bFrameMachine_Pause
	mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_EStop = mem.v_GlobalVars.v_fbExternalDevice.v_q_bFrameMachine_EStop
	mem.v_GlobalVars.v_stExternal.v_o_bDoorOpenRequest = mem.v_GlobalVars.v_fbExternalDevice.v_q_bDoorOpenRequest
	mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_Ready = mem.v_GlobalVars.v_fbExternalDevice.v_q_bFrameMachine_Ready
	mem.v_GlobalVars.v_stExternal.v_o_bGlueMachine_RequestRun = mem.v_GlobalVars.v_fbExternalDevice.v_q_bGlueMachine_RequestRun
	mem.v_GlobalVars.v_stExternal.v_o_bAllowPickup = mem.v_GlobalVars.v_fbExternalDevice.v_q_bAllowPickup
	mem.v_GlobalVars.v_stExternal.v_o_bSafetyZoneSignal = mem.v_GlobalVars.v_fbExternalDevice.v_q_bSafetyZoneSignal
	mem.v_GlobalVars.v_stExternal.v_o_bGlueMachine_ResetReq = mem.v_GlobalVars.v_fbExternalDevice.v_q_bGlueMachine_ResetReq
	mem.v_GlobalVars.v_stExternal.v_o_bRobot_AllowStacking = mem.v_GlobalVars.v_fbExternalDevice.v_q_bRobot_AllowStacking
	mem.v_GlobalVars.v_stExternal.v_o_bRobot_StopStacking = mem.v_GlobalVars.v_fbExternalDevice.v_q_bRobot_StopStacking
	mem.v_GlobalVars.v_stExternal.v_o_bRobot_ResetReq = mem.v_GlobalVars.v_fbExternalDevice.v_q_bRobot_ResetReq
	mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_EmergencyStop = mem.v_GlobalVars.v_fbExternalDevice.v_q_bFrameMachine_EmergencyStop
	mem.v_GlobalVars.v_stExternal.v_o_bExternalDeviceFault = mem.v_GlobalVars.v_fbExternalDevice.v_q_bExternalDeviceFault
	mem.v_GlobalVars.v_stExternal.v_o_iExternalDeviceAlarmSummary = int16(mem.v_GlobalVars.v_fbExternalDevice.v_q_iExternalDeviceAlarmSummary)
	mem.v_GlobalVars.v_stExternal.v_o_bSystemSafetyConditionMet = mem.v_GlobalVars.v_fbExternalDevice.v_q_bSystemSafetyConditionMet
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:94:5
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bEnable = mem.v_GlobalVars.v_stConveyor.v_i_bEnable
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bAutoMode = mem.v_GlobalVars.v_stConveyor.v_i_bAutoMode
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bManualMode = mem.v_GlobalVars.v_stConveyor.v_i_bManualMode
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bStart = mem.v_GlobalVars.v_stConveyor.v_i_bStart
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bStop = mem.v_GlobalVars.v_stConveyor.v_i_bStop
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bReset = mem.v_GlobalVars.v_stConveyor.v_i_bReset
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_rConveyorSpeed = float32(mem.v_GlobalVars.v_stConveyor.v_i_rConveyorSpeed)
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_iSeparateTime = int16(mem.v_GlobalVars.v_stConveyor.v_i_iSeparateTime)
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_iBlockWaitTime = int16(mem.v_GlobalVars.v_stConveyor.v_i_iBlockWaitTime)
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bLx_BlockDown = mem.v_GlobalVars.v_stConveyor.v_i_bLx_BlockDown
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bLx_BlockUp = mem.v_GlobalVars.v_stConveyor.v_i_bLx_BlockUp
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bLx_SeparatePush = mem.v_GlobalVars.v_stConveyor.v_i_bLx_SeparatePush
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bLx_SeparateReset = mem.v_GlobalVars.v_stConveyor.v_i_bLx_SeparateReset
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bLx_ConveyorFwd = mem.v_GlobalVars.v_stConveyor.v_i_bLx_ConveyorFwd
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bLx_ConveyorRev = mem.v_GlobalVars.v_stConveyor.v_i_bLx_ConveyorRev
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bPreSeparateSensor = mem.v_GlobalVars.v_stConveyor.v_i_bPreSeparateSensor
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bPositionSensor1 = mem.v_GlobalVars.v_stConveyor.v_i_bPositionSensor1
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bPositionSensor2 = mem.v_GlobalVars.v_stConveyor.v_i_bPositionSensor2
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bBlockCylinderUp = mem.v_GlobalVars.v_stConveyor.v_i_bBlockCylinderUp
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bBlockCylinderDown = mem.v_GlobalVars.v_stConveyor.v_i_bBlockCylinderDown
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bSeparateCylinderUp = mem.v_GlobalVars.v_stConveyor.v_i_bSeparateCylinderUp
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bSeparateCylinderDown = mem.v_GlobalVars.v_stConveyor.v_i_bSeparateCylinderDown
	mem.v_GlobalVars.v_fbConveyor4Layer.v_i_bFeedComplete = mem.v_GlobalVars.v_stConveyor.v_i_bFeedComplete
	FB_FB_1001_Conveyor4Layer_BufferFraming(mem, &mem.v_GlobalVars.v_fbConveyor4Layer)
	mem.v_GlobalVars.v_stConveyor.v_o_bBlockSolenoid = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bBlockSolenoid
	mem.v_GlobalVars.v_stConveyor.v_o_bSeparateSolenoid = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bSeparateSolenoid
	mem.v_GlobalVars.v_stConveyor.v_o_bConveyorFwd = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bConveyorFwd
	mem.v_GlobalVars.v_stConveyor.v_o_bConveyorSlow = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bConveyorSlow
	mem.v_GlobalVars.v_stConveyor.v_o_bConveyorRev = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bConveyorRev
	mem.v_GlobalVars.v_stConveyor.v_o_bFeedComplete = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bFeedComplete
	mem.v_GlobalVars.v_stConveyor.v_o_bRunning = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bRunning
	mem.v_GlobalVars.v_stConveyor.v_o_bFault = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_bFault
	mem.v_GlobalVars.v_stConveyor.v_o_iCurrentState = int16(mem.v_GlobalVars.v_fbConveyor4Layer.v_o_iCurrentState)
	mem.v_GlobalVars.v_stConveyor.v_o_LxCurrentStep = mem.v_GlobalVars.v_fbConveyor4Layer.v_o_LxCurrentStep
	mem.v_GlobalVars.v_stConveyor.v_o_iAlarmCode = int16(mem.v_GlobalVars.v_fbConveyor4Layer.v_o_iAlarmCode)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:141:5
	mem.v_GlobalVars.v_fbPickPlace.v_i_bAutoMode = mem.v_GlobalVars.v_stPickPlace.v_i_bAutoMode
	mem.v_GlobalVars.v_fbPickPlace.v_i_bManualMode = mem.v_GlobalVars.v_stPickPlace.v_i_bManualMode
	mem.v_GlobalVars.v_fbPickPlace.v_i_bStart = mem.v_GlobalVars.v_stPickPlace.v_i_bStart
	mem.v_GlobalVars.v_fbPickPlace.v_i_bStop = mem.v_GlobalVars.v_stPickPlace.v_i_bStop
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLx_FrontClamp = mem.v_GlobalVars.v_stPickPlace.v_i_bLx_FrontClamp
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLx_RearClamp = mem.v_GlobalVars.v_stPickPlace.v_i_bLx_RearClamp
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLx_FrontClamp2 = mem.v_GlobalVars.v_stPickPlace.v_i_bLx_FrontClamp2
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLx_RearClamp2 = mem.v_GlobalVars.v_stPickPlace.v_i_bLx_RearClamp2
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLx_LiftUp = mem.v_GlobalVars.v_stPickPlace.v_i_bLx_Lift_Up
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLx_LiftDown = mem.v_GlobalVars.v_stPickPlace.v_i_bLx_Lift_Down
	mem.v_GlobalVars.v_fbPickPlace.v_i_iPickLayer = int16(mem.v_GlobalVars.v_stPickPlace.v_o_iCurrentPickLayer)
	mem.v_GlobalVars.v_fbPickPlace.v_i_rZSpeed = float32(mem.v_GlobalVars.v_stPickPlace.v_i_rZAxisSpeed)
	mem.v_GlobalVars.v_fbPickPlace.v_i_rX1Speed = float32(mem.v_GlobalVars.v_stPickPlace.v_i_rX1AxisSpeed)
	mem.v_GlobalVars.v_fbPickPlace.v_i_iClampConfirmTime = int16(mem.v_GlobalVars.v_stPickPlace.v_i_iClampConfirmTime)
	mem.v_GlobalVars.v_fbPickPlace.v_i_iLiftActionTime = int16(mem.v_GlobalVars.v_stPickPlace.v_i_iLiftActionTime)
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLayerFeedDone = mem.v_GlobalVars.v_stConveyor.v_o_bFeedComplete
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLongEdge1Detect = mem.v_GlobalVars.v_stPickPlace.v_i_bLongEdge1Detect
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLongEdge2Detect = mem.v_GlobalVars.v_stPickPlace.v_i_bLongEdge2Detect
	mem.v_GlobalVars.v_fbPickPlace.v_i_bShortEdge1Detect = mem.v_GlobalVars.v_stPickPlace.v_i_bShortEdge1Detect
	mem.v_GlobalVars.v_fbPickPlace.v_i_bShortEdge2Detect = mem.v_GlobalVars.v_stPickPlace.v_i_bShortEdge2Detect
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFrontClampClosed = mem.v_GlobalVars.v_stPickPlace.v_i_bFrontClamp_Closed
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFrontClampOpened = mem.v_GlobalVars.v_stPickPlace.v_i_bFrontClamp_Opened
	mem.v_GlobalVars.v_fbPickPlace.v_i_bRearClampClosed = mem.v_GlobalVars.v_stPickPlace.v_i_bRearClamp_Closed
	mem.v_GlobalVars.v_fbPickPlace.v_i_bRearClampOpened = mem.v_GlobalVars.v_stPickPlace.v_i_bRearClamp_Opened
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFrontClamp2Closed = mem.v_GlobalVars.v_stPickPlace.v_i_bFrontClamp2_Closed
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFrontClamp2Opened = mem.v_GlobalVars.v_stPickPlace.v_i_bFrontClamp2_Opened
	mem.v_GlobalVars.v_fbPickPlace.v_i_bRearClamp2Closed = mem.v_GlobalVars.v_stPickPlace.v_i_bRearClamp2_Closed
	mem.v_GlobalVars.v_fbPickPlace.v_i_bRearClamp2Opened = mem.v_GlobalVars.v_stPickPlace.v_i_bRearClamp2_Opened
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLiftHomePos = mem.v_GlobalVars.v_stPickPlace.v_i_bLift_HomePos
	mem.v_GlobalVars.v_fbPickPlace.v_i_bLiftWorkPoint = mem.v_GlobalVars.v_stPickPlace.v_i_bLift_WorkPoint
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFrameDetect1 = false
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFrameDetect2 = false
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFullMaterialDetect1 = false
	mem.v_GlobalVars.v_fbPickPlace.v_i_bFullMaterialDetect2 = false
	FB_FB_1003_PickPlace_BufferFraming(mem, &mem.v_GlobalVars.v_fbPickPlace)
	mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Action = mem.v_GlobalVars.v_fbPickPlace.v_q_bFrontClamp
	mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Action = mem.v_GlobalVars.v_fbPickPlace.v_q_bRearClamp
	mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp2_Action = mem.v_GlobalVars.v_fbPickPlace.v_q_bFrontClamp2
	mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp2_Action = mem.v_GlobalVars.v_fbPickPlace.v_q_bRearClamp2
	mem.v_GlobalVars.v_stPickPlace.v_o_bLift_Up = mem.v_GlobalVars.v_fbPickPlace.v_q_bLiftUp
	mem.v_GlobalVars.v_stPickPlace.v_o_bLift_Down = mem.v_GlobalVars.v_fbPickPlace.v_q_bLiftDown
	mem.v_GlobalVars.v_stPickPlace.v_o_iCurrentState = int16(mem.v_GlobalVars.v_fbPickPlace.v_q_iCurrentState)
	mem.v_GlobalVars.v_stPickPlace.v_o_iCurrentPickLayer = int16(mem.v_GlobalVars.v_fbPickPlace.v_q_iCurrentPickLayer)
	mem.v_GlobalVars.v_stPickPlace.v_o_iStationAlarmCode = int16(mem.v_GlobalVars.v_fbPickPlace.v_q_iAlarmCode)
	mem.v_GlobalVars.v_stPickPlace.v_o_bPlaceComplete_ToFeeder = mem.v_GlobalVars.v_fbPickPlace.v_q_bPlaceDoneToFeeder
	mem.v_GlobalVars.v_stPickPlace.v_o_bRunning = mem.v_GlobalVars.v_fbPickPlace.v_q_bRunning
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:199:5
	mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Release = !(mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Action)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:200:5
	mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Release = !(mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Action)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:201:5
	mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp2_Release = !(mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp2_Action)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:202:5
	mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp2_Release = !(mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp2_Action)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:208:5
	mem.v_GlobalVars.v_stFeeder.v_i_bPickPlace_FeedComplete = mem.v_GlobalVars.v_stPickPlace.v_o_bPlaceComplete_ToFeeder
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:210:5
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bAutoMode = mem.v_GlobalVars.v_stFeeder.v_i_bAutoMode
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bManualMode = mem.v_GlobalVars.v_stFeeder.v_i_bManualMode
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bStart = mem.v_GlobalVars.v_stFeeder.v_i_bStart
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bStop = mem.v_GlobalVars.v_stFeeder.v_i_bStop
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bLx_X2JogPos = mem.v_GlobalVars.v_stFeeder.v_i_bLx_X2Axis_JogFwd
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bLx_X2JogNeg = mem.v_GlobalVars.v_stFeeder.v_i_bLx_X2Axis_JogRev
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bPlaceDone = mem.v_GlobalVars.v_stFeeder.v_i_bPickPlace_FeedComplete
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_rX2Speed = float32(mem.v_GlobalVars.v_stFeeder.v_i_rFeedSpeed)
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bGlueMachineAllowFeed = mem.v_GlobalVars.v_stFeeder.v_i_bGlueMachine_AllowFeed
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bGlueMachinePickupComplete = mem.v_GlobalVars.v_stFeeder.v_i_bGlueMachine_PickupComplete
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bX2ZoneSensor1 = false
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bX2ZoneSensor2 = false
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bX2ZoneSensor3 = false
	mem.v_GlobalVars.v_fbGlueFeeder.v_i_bX2ZoneSensor4 = false
	FB_FB_1004_GlueMachineFeeder_BufferFraming(mem, &mem.v_GlobalVars.v_fbGlueFeeder)
	mem.v_GlobalVars.v_stFeeder.v_o_bX2Axis_RequestFwd = mem.v_GlobalVars.v_fbGlueFeeder.v_q_bX2AxisMoveAbsReq
	mem.v_GlobalVars.v_stFeeder.v_o_bAllowPickup = mem.v_GlobalVars.v_fbGlueFeeder.v_q_bAllowPickup
	mem.v_GlobalVars.v_stFeeder.v_o_bSafetyZoneSignal = mem.v_GlobalVars.v_fbGlueFeeder.v_q_bSafetyZoneSignal
	mem.v_GlobalVars.v_stFeeder.v_o_iCurrentState = int16(mem.v_GlobalVars.v_fbGlueFeeder.v_q_iCurrentState)
	mem.v_GlobalVars.v_stFeeder.v_o_iStationAlarmCode = int16(mem.v_GlobalVars.v_fbGlueFeeder.v_q_iAlarmCode)
	mem.v_GlobalVars.v_stFeeder.v_o_bRunning = mem.v_GlobalVars.v_fbGlueFeeder.v_q_bRunning
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-005/02_PLC程序/通用ST程序及变量表/OB1/OB1.scl:241:5
	mem.v_GlobalVars.v_fbCommonAlarm.v_i_iConveyorAlarm = int16(mem.v_GlobalVars.v_stConveyor.v_o_iAlarmCode)
	mem.v_GlobalVars.v_fbCommonAlarm.v_i_iPickPlaceAlarm = int16(mem.v_GlobalVars.v_stPickPlace.v_o_iStationAlarmCode)
	mem.v_GlobalVars.v_fbCommonAlarm.v_i_iFeederAlarm = int16(mem.v_GlobalVars.v_stFeeder.v_o_iStationAlarmCode)
	mem.v_GlobalVars.v_fbCommonAlarm.v_i_bReset = mem.v_GlobalVars.v_stGlobal.v_i_bReset
	FB_FB_2001_CommonAlarm_AllStation(mem, &mem.v_GlobalVars.v_fbCommonAlarm)
	mem.v_GlobalVars.v_stGlobal.v_o_wGlobalAlarmWord = uint16(mem.v_GlobalVars.v_fbCommonAlarm.v_o_wGlobalAlarmWord)
	mem.v_GlobalVars.v_stGlobal.v_o_iCurrentAlarmCode = int16(mem.v_GlobalVars.v_fbCommonAlarm.v_o_iCurrentAlarmCode)
	mem.v_GlobalVars.v_stGlobal.v_o_bAnyAlarmActive = mem.v_GlobalVars.v_fbCommonAlarm.v_o_bAnyAlarmActive
	mem.v_GlobalVars.v_stGlobal.v_o_iMESAlarmCount = int16(mem.v_GlobalVars.v_fbCommonAlarm.v_o_iMESAlarmCount)
	mem.v_GlobalVars.v_stGlobal.v_o_iMESAlarmQueue = mem.v_GlobalVars.v_fbCommonAlarm.v_o_iMESAlarmQueue
	mem.v_GlobalVars.v_stGlobal.v_o_bNewAlarmFlag = mem.v_GlobalVars.v_fbCommonAlarm.v_o_bNewAlarmFlag
	mem.v_GlobalVars.v_stGlobal.v_o_iStationAlarmStatus = mem.v_GlobalVars.v_fbCommonAlarm.v_o_iStationAlarmStatus
	mem.v_GlobalVars.v_stGlobal.v_o_bConveyorAlarmActive = mem.v_GlobalVars.v_fbCommonAlarm.v_o_bConveyorAlarmActive
	mem.v_GlobalVars.v_stGlobal.v_o_bPickPlaceAlarmActive = mem.v_GlobalVars.v_fbCommonAlarm.v_o_bPickPlaceAlarmActive
	mem.v_GlobalVars.v_stGlobal.v_o_bFeederAlarmActive = mem.v_GlobalVars.v_fbCommonAlarm.v_o_bFeederAlarmActive
}
