// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"fmt"
	"plc-autogen/builtins"
	"testing"
)

type TestObservationHooks interface {
	OnTestStart(TestStartEvent)
	OnStep(TestStepEvent)
	OnAssert(TestAssertEvent)
	OnTestComplete(TestCompleteEvent)
}

type TestStartEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
}

type TestStepEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	ClockNow   TIME
}

type TestAssertEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	Passed     bool
	Condition  string
	Operator   string
	Got        string
	Expected   string
	Tolerance  string
	ClockNow   TIME
}

type TestCompleteEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Passed     bool
	Steps      int
	ClockNow   TIME
}

type TestRuntimeContext struct {
	Hooks TestObservationHooks
}

func NewTestRuntimeContext(hooks TestObservationHooks) *TestRuntimeContext {
	return &TestRuntimeContext{Hooks: hooks}
}

func observeTestStart(ctx *TestRuntimeContext, event TestStartEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestStart(event)
	}
}

func observeTestStep(ctx *TestRuntimeContext, event TestStepEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnStep(event)
	}
}

func observeTestAssert(ctx *TestRuntimeContext, event TestAssertEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnAssert(event)
	}
}

func observeTestComplete(ctx *TestRuntimeContext, event TestCompleteEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestComplete(event)
	}
}

func testObservationString(value any) string {
	return fmt.Sprint(value)
}

func resetGeneratedTestBuiltinsState() {
	builtins.ResetGeneratedTestState()
}

func resetGeneratedTestRuntimeState() {
	resetGeneratedTestBuiltinsState()

}

func TestUserCase001_TC01ExternalReady(t *testing.T) {
	t.Parallel()
	runTestUserCase001_TC01ExternalReady(t, nil)
}

func runTestUserCase001_TC01ExternalReady(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 28, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 28, Column: 1, Passed: passed, Steps: 5, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 35, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bEnable = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 36, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bAutoMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 37, Column: 5, Step: 3, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bAnyAlarmActive = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 38, Column: 5, Step: 4, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 39, Column: 5, Step: 5, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_Ready
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_Ready == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC01_External_Ready", StableID: "scltest:Test/basic_test.scltest:L28:C1:TC01_External_Ready", SourcePath: "Test/basic_test.scltest", Line: 39, Column: 5, Step: 5, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_bFrameMachine_Ready = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:39:5 step 5: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase002_TC02ExternalEStop(t *testing.T) {
	t.Parallel()
	runTestUserCase002_TC02ExternalEStop(t, nil)
}

func runTestUserCase002_TC02ExternalEStop(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC02_External_EStop", StableID: "scltest:Test/basic_test.scltest:L42:C1:TC02_External_EStop", SourcePath: "Test/basic_test.scltest", Line: 42, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC02_External_EStop", StableID: "scltest:Test/basic_test.scltest:L42:C1:TC02_External_EStop", SourcePath: "Test/basic_test.scltest", Line: 42, Column: 1, Passed: passed, Steps: 3, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC02_External_EStop", StableID: "scltest:Test/basic_test.scltest:L42:C1:TC02_External_EStop", SourcePath: "Test/basic_test.scltest", Line: 49, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bFrameMachine_EStop = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC02_External_EStop", StableID: "scltest:Test/basic_test.scltest:L42:C1:TC02_External_EStop", SourcePath: "Test/basic_test.scltest", Line: 50, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC02_External_EStop", StableID: "scltest:Test/basic_test.scltest:L42:C1:TC02_External_EStop", SourcePath: "Test/basic_test.scltest", Line: 51, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_EmergencyStop
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_EmergencyStop == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC02_External_EStop", StableID: "scltest:Test/basic_test.scltest:L42:C1:TC02_External_EStop", SourcePath: "Test/basic_test.scltest", Line: 51, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_bFrameMachine_EmergencyStop = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:51:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase003_TC03ExternalAlarm(t *testing.T) {
	t.Parallel()
	runTestUserCase003_TC03ExternalAlarm(t, nil)
}

func runTestUserCase003_TC03ExternalAlarm(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC03_External_Alarm", StableID: "scltest:Test/basic_test.scltest:L54:C1:TC03_External_Alarm", SourcePath: "Test/basic_test.scltest", Line: 54, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC03_External_Alarm", StableID: "scltest:Test/basic_test.scltest:L54:C1:TC03_External_Alarm", SourcePath: "Test/basic_test.scltest", Line: 54, Column: 1, Passed: passed, Steps: 3, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC03_External_Alarm", StableID: "scltest:Test/basic_test.scltest:L54:C1:TC03_External_Alarm", SourcePath: "Test/basic_test.scltest", Line: 61, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bGlueMachine_Fault = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC03_External_Alarm", StableID: "scltest:Test/basic_test.scltest:L54:C1:TC03_External_Alarm", SourcePath: "Test/basic_test.scltest", Line: 62, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC03_External_Alarm", StableID: "scltest:Test/basic_test.scltest:L54:C1:TC03_External_Alarm", SourcePath: "Test/basic_test.scltest", Line: 63, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_iExternalDeviceAlarmSummary
		expectedValue := 300
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_iExternalDeviceAlarmSummary == 300)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC03_External_Alarm", StableID: "scltest:Test/basic_test.scltest:L54:C1:TC03_External_Alarm", SourcePath: "Test/basic_test.scltest", Line: 63, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_iExternalDeviceAlarmSummary = 300", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:63:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase004_TC04ExternalSafety(t *testing.T) {
	t.Parallel()
	runTestUserCase004_TC04ExternalSafety(t, nil)
}

func runTestUserCase004_TC04ExternalSafety(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC04_External_Safety", StableID: "scltest:Test/basic_test.scltest:L66:C1:TC04_External_Safety", SourcePath: "Test/basic_test.scltest", Line: 66, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC04_External_Safety", StableID: "scltest:Test/basic_test.scltest:L66:C1:TC04_External_Safety", SourcePath: "Test/basic_test.scltest", Line: 66, Column: 1, Passed: passed, Steps: 2, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC04_External_Safety", StableID: "scltest:Test/basic_test.scltest:L66:C1:TC04_External_Safety", SourcePath: "Test/basic_test.scltest", Line: 73, Column: 5, Step: 1, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC04_External_Safety", StableID: "scltest:Test/basic_test.scltest:L66:C1:TC04_External_Safety", SourcePath: "Test/basic_test.scltest", Line: 74, Column: 5, Step: 2, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_bSystemSafetyConditionMet
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_bSystemSafetyConditionMet == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC04_External_Safety", StableID: "scltest:Test/basic_test.scltest:L66:C1:TC04_External_Safety", SourcePath: "Test/basic_test.scltest", Line: 74, Column: 5, Step: 2, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_bSystemSafetyConditionMet = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:74:5 step 2: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase005_TC05ExternalDoorOpen(t *testing.T) {
	t.Parallel()
	runTestUserCase005_TC05ExternalDoorOpen(t, nil)
}

func runTestUserCase005_TC05ExternalDoorOpen(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 77, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 77, Column: 1, Passed: passed, Steps: 4, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 84, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stExternal.v_i_bDoorOpenRequest = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 85, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 86, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_Pause
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_bFrameMachine_Pause == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 86, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_bFrameMachine_Pause = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:86:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 87, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stExternal.v_o_bDoorOpenRequest
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stExternal.v_o_bDoorOpenRequest == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC05_External_DoorOpen", StableID: "scltest:Test/basic_test.scltest:L77:C1:TC05_External_DoorOpen", SourcePath: "Test/basic_test.scltest", Line: 87, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stExternal.o_bDoorOpenRequest = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:87:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase006_TC06PickPlaceClamp(t *testing.T) {
	t.Parallel()
	runTestUserCase006_TC06PickPlaceClamp(t, nil)
}

func runTestUserCase006_TC06PickPlaceClamp(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 90, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 90, Column: 1, Passed: passed, Steps: 5, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 98, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stPickPlace.v_i_bManualMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 99, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stPickPlace.v_i_bLx_FrontClamp = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 100, Column: 5, Step: 3, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 101, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Action
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Action == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 101, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bFrontClamp_Action = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:101:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 102, Column: 5, Step: 5, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Release
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Release == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC06_PickPlace_Clamp", StableID: "scltest:Test/basic_test.scltest:L90:C1:TC06_PickPlace_Clamp", SourcePath: "Test/basic_test.scltest", Line: 102, Column: 5, Step: 5, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bFrontClamp_Release = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:102:5 step 5: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase007_TC07PickPlaceLiftUp(t *testing.T) {
	t.Parallel()
	runTestUserCase007_TC07PickPlaceLiftUp(t, nil)
}

func runTestUserCase007_TC07PickPlaceLiftUp(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 105, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 105, Column: 1, Passed: passed, Steps: 5, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 112, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stPickPlace.v_i_bManualMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 113, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stPickPlace.v_i_bLx_Lift_Up = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 114, Column: 5, Step: 3, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 115, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bLift_Up
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bLift_Up == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 115, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bLift_Up = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:115:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 116, Column: 5, Step: 5, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bLift_Down
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bLift_Down == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC07_PickPlace_LiftUp", StableID: "scltest:Test/basic_test.scltest:L105:C1:TC07_PickPlace_LiftUp", SourcePath: "Test/basic_test.scltest", Line: 116, Column: 5, Step: 5, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bLift_Down = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:116:5 step 5: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase008_TC08PickPlaceUnclamp(t *testing.T) {
	t.Parallel()
	runTestUserCase008_TC08PickPlaceUnclamp(t, nil)
}

func runTestUserCase008_TC08PickPlaceUnclamp(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 119, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 119, Column: 1, Passed: passed, Steps: 6, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 127, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stPickPlace.v_i_bManualMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 128, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 129, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Action
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Action == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 129, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bFrontClamp_Action = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:129:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 130, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Release
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bFrontClamp_Release == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 130, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bFrontClamp_Release = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:130:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 131, Column: 5, Step: 5, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Action
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Action == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 131, Column: 5, Step: 5, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bRearClamp_Action = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:131:5 step 5: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 132, Column: 5, Step: 6, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Release
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_stPickPlace.v_o_bRearClamp_Release == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC08_PickPlace_Unclamp", StableID: "scltest:Test/basic_test.scltest:L119:C1:TC08_PickPlace_Unclamp", SourcePath: "Test/basic_test.scltest", Line: 132, Column: 5, Step: 6, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stPickPlace.o_bRearClamp_Release = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:132:5 step 6: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase009_TC09CommonAlarmReset(t *testing.T) {
	t.Parallel()
	runTestUserCase009_TC09CommonAlarmReset(t, nil)
}

func runTestUserCase009_TC09CommonAlarmReset(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 135, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 135, Column: 1, Passed: passed, Steps: 6, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 142, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stGlobal.v_i_bReset = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 143, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(3)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 144, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_wGlobalAlarmWord
		expectedValue := 0
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_wGlobalAlarmWord == 0)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 144, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_wGlobalAlarmWord = 0", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:144:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 145, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_iCurrentAlarmCode
		expectedValue := 0
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_iCurrentAlarmCode == 0)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 145, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_iCurrentAlarmCode = 0", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:145:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 146, Column: 5, Step: 5, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_bAnyAlarmActive
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_bAnyAlarmActive == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 146, Column: 5, Step: 5, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_bAnyAlarmActive = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:146:5 step 5: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 147, Column: 5, Step: 6, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_iMESAlarmCount
		expectedValue := 0
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_iMESAlarmCount == 0)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC09_CommonAlarm_Reset", StableID: "scltest:Test/basic_test.scltest:L135:C1:TC09_CommonAlarm_Reset", SourcePath: "Test/basic_test.scltest", Line: 147, Column: 5, Step: 6, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_iMESAlarmCount = 0", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:147:5 step 6: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase010_TC10CommonAlarmNoAlarm(t *testing.T) {
	t.Parallel()
	runTestUserCase010_TC10CommonAlarmNoAlarm(t, nil)
}

func runTestUserCase010_TC10CommonAlarmNoAlarm(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 150, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 150, Column: 1, Passed: passed, Steps: 9, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 157, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stConveyor.v_i_bManualMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 158, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stPickPlace.v_i_bManualMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 159, Column: 5, Step: 3, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stFeeder.v_i_bManualMode = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 160, Column: 5, Step: 4, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_stGlobal.v_i_bReset = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 161, Column: 5, Step: 5, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(5)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 162, Column: 5, Step: 6, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_bAnyAlarmActive
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_bAnyAlarmActive == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 162, Column: 5, Step: 6, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_bAnyAlarmActive = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:162:5 step 6: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 163, Column: 5, Step: 7, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_bConveyorAlarmActive
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_bConveyorAlarmActive == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 163, Column: 5, Step: 7, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_bConveyorAlarmActive = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:163:5 step 7: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 164, Column: 5, Step: 8, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_bPickPlaceAlarmActive
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_bPickPlaceAlarmActive == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 164, Column: 5, Step: 8, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_bPickPlaceAlarmActive = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:164:5 step 8: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 165, Column: 5, Step: 9, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_stGlobal.v_o_bFeederAlarmActive
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_stGlobal.v_o_bFeederAlarmActive == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "TC10_CommonAlarm_NoAlarm", StableID: "scltest:Test/basic_test.scltest:L150:C1:TC10_CommonAlarm_NoAlarm", SourcePath: "Test/basic_test.scltest", Line: 165, Column: 5, Step: 9, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.stGlobal.o_bFeederAlarmActive = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/basic_test.scltest:165:5 step 9: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}
