TYPE ST_CylinderCmd :
STRUCT
    Extend          : BOOL := FALSE;   // 动点命令: 伸出/真空ON/夹紧/下降
    Retract         : BOOL := FALSE;   // 原点命令: 收回/破真空/松开/上升
    ExtendedPos     : BOOL := FALSE;   // 动点到位
    RetractedPos    : BOOL := FALSE;   // 原点到位
    TimeoutMs       : DINT := 5000;
    DebounceMs      : DINT := 0;
    SolenoidType    : INT := 0;
    ExtendPolarity  : BOOL := FALSE;
    RetractPolarity : BOOL := FALSE;
    Mode            : INT := 1;
    ModeStatus      : WORD := 16#0000;
END_STRUCT;
END_TYPE

TYPE ST_CylinderSts :
STRUCT
    SolenoidA       : BOOL := FALSE;   // 线圈A输出
    SolenoidB       : BOOL := FALSE;   // 线圈B输出
    IsExtended      : BOOL := FALSE;   // 已到动点
    IsRetracted     : BOOL := FALSE;   // 已到原点
    Timeout         : BOOL := FALSE;   // 动作超时报警
    SensorFault     : BOOL := FALSE;   // 传感器冲突
END_STRUCT;
END_TYPE

TYPE ST_Cylinder :
STRUCT
    Extend          : BOOL := FALSE;   // 动点命令: 伸出/真空ON/夹紧/下降
    Retract         : BOOL := FALSE;   // 原点命令: 收回/破真空/松开/上升
    ExtendedPos     : BOOL := FALSE;   // 动点到位
    RetractedPos    : BOOL := FALSE;   // 原点到位
    TimeoutMs       : DINT := 5000;
    DebounceMs      : DINT := 0;
    SolenoidType    : INT := 0;
    ExtendPolarity  : BOOL := FALSE;
    RetractPolarity : BOOL := FALSE;
    Mode            : INT := 1;
    ModeStatus      : WORD := 16#0000;
    stCmd           : ST_CylinderCmd;
    stSts           : ST_CylinderSts;
END_STRUCT;
END_TYPE