const state = {
  activeActivity: 'dashboard',
  activeTab: 'dashboard',
  sidebarCollapsed: false,
  bottomPanelOpen: true,
  bottomPanelActiveTab: 'output',
  openTabs: ['dashboard'],
  collapseState: {
    project: true,
    document: false,
    tools: false,
    change: false,
    spec: false,
  },
  checkerSelections: {
    syntax:   true,
    comment:  true,
    naming:   true,
    variable: true,
    config:   false,
    timer:    false,
    fb_iface: true,
  },
  currentProject: null,
  currentProjectPath: '',
  dashboardStats: { project_count: 0, template_count: 0, recent_projects: [] },
  changeRequests: [],
  checkers: [],
  specResults: null,
  diagnosticResults: null,
  fixers: [],
  fixResults: null,
  settings: {},
  isLoading: false,
};
