# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_src_path: C:\Users\fubai\Desktop\My_Workspace\01_Project自动化项目管理\Python自动化项目总库\02_在研项目\SW-2026-008_auto-pm_自动化项目管理工具\templates\plc-standard
description: GUI自动化测试临时项目
project_id: DJ-2026-998
project_name: GUI自动化测试临时项目
version: V1.0.0

