// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:23:1
func FB_FB_ValveControl(mem *Memory, db *DB_FB_ValveControl) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:79:5
	if db.v_OverCurrent {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:80:9
		db.v_FaultLocked = true
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:81:9
		db.v_FaultStatus = true
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:84:9
		db.v_ValveOpen = false
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:85:9
		db.v_ValveClose = false
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:86:9
		db.v_ValveState = int16(0)
	}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:90:5
	if db.v_FaultReset && !(db.v_OverCurrent) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:91:9
		db.v_FaultLocked = false
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:92:9
		db.v_FaultStatus = false
	}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:96:5
	if db.v_FaultLocked {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:97:9
		return
	}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:104:5
	if db.v_AutoManual {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:109:9
		if db.v_OpenCmd && !(db.v_OPENCMD_R) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:111:13
			if db.v_ValveState != 2 {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:112:17
				db.v_ValveState = int16(1)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:113:17
				db.v_ValveOpen = true
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:114:17
				db.v_ValveClose = false
			}
		}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:121:9
		if db.v_CloseCmd {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:123:13
			if db.v_ValveState != 0 {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:124:17
				db.v_ValveState = int16(3)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:125:17
				db.v_ValveClose = true
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:126:17
				db.v_ValveOpen = false
			}
		}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:134:9
		if db.v_OpenLimit && (db.v_ValveState == 1) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:135:13
			db.v_ValveState = int16(2)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:136:13
			db.v_ValveOpen = false
		}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:140:9
		if db.v_CloseLimit && (db.v_ValveState == 3) {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:141:13
			db.v_ValveState = int16(0)
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:142:13
			db.v_ValveClose = false
		}
	} else {
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:148:9
		db.v_ValveOpen = false
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:149:9
		db.v_ValveClose = false
	}
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:155:5
	db.v_OPENCMD_R = db.v_OpenCmd
//line c:/Users/fubai/Desktop/My_Workspace/0100_PLC自动化/DJ-2026-000/FB100/FB_ValveControl.scl:156:5
	db.v_CLOSECMD_R = db.v_CloseCmd
}
