// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:19:1
func OB_OB1(mem *Memory) {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:26:1
	mem.v_GlobalVars.v_ValveCtrl.v_AutoManual = mem.v_GlobalVars.v_Hmibutton[0]
	mem.v_GlobalVars.v_ValveCtrl.v_OpenCmd = mem.v_GlobalVars.v_Hmibutton[1]
	mem.v_GlobalVars.v_ValveCtrl.v_CloseCmd = mem.v_GlobalVars.v_Hmibutton[2]
	mem.v_GlobalVars.v_ValveCtrl.v_OverCurrent = mem.v_GlobalVars.v_Hmibutton[3]
	mem.v_GlobalVars.v_ValveCtrl.v_OpenLimit = mem.v_GlobalVars.v_Hmibutton[4]
	mem.v_GlobalVars.v_ValveCtrl.v_CloseLimit = mem.v_GlobalVars.v_Hmibutton[5]
	mem.v_GlobalVars.v_ValveCtrl.v_FaultReset = mem.v_GlobalVars.v_Hmibutton[6]
	FB_FB_ValveControl(mem, &mem.v_GlobalVars.v_ValveCtrl)
	mem.v_GlobalVars.v_FaultStatus = mem.v_GlobalVars.v_ValveCtrl.v_FaultStatus
	mem.v_GlobalVars.v_ValveOpen = mem.v_GlobalVars.v_ValveCtrl.v_ValveOpen
	mem.v_GlobalVars.v_ValveClose = mem.v_GlobalVars.v_ValveCtrl.v_ValveClose
	mem.v_GlobalVars.v_ValveState = int16(mem.v_GlobalVars.v_ValveCtrl.v_ValveState)
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:48:1
	if mem.v_GlobalVars.v_Hmibutton[7] {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:49:5
		mem.v_GlobalVars.v_COUNTER_A = int32((mem.v_GlobalVars.v_COUNTER_A + 1))
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:51:5
		if mem.v_GlobalVars.v_COUNTER_A >= 50 {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:52:9
			mem.v_GlobalVars.v_BOUT_A = true
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:53:9
			mem.v_GlobalVars.v_COUNTER_A = int32(50)
		}
	} else {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:56:5
		mem.v_GlobalVars.v_BOUT_A = false
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:57:5
		mem.v_GlobalVars.v_COUNTER_A = int32(0)
	}
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:64:1
	if mem.v_GlobalVars.v_Hmibutton[8] {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:65:5
		mem.v_GlobalVars.v_COUNTER_B = int32((mem.v_GlobalVars.v_COUNTER_B + 1))
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:67:5
		if mem.v_GlobalVars.v_COUNTER_B >= 50 {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:68:9
			mem.v_GlobalVars.v_BOUT_B = true
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:69:9
			mem.v_GlobalVars.v_COUNTER_B = int32(50)
		}
	} else {
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:72:5
		mem.v_GlobalVars.v_BOUT_B = false
//line d:/BaiduSyncdisk/My_Workspace/0100_PLC自动化/DJ-2026-000/OB1/OB1.scl:73:5
		mem.v_GlobalVars.v_COUNTER_B = int32(0)
	}
}
