// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

type Memory struct {
	SCLH_CycleLastNS      int64
	SCLH_CycleLongestNS   int64
	SCLH_CycleShortestNS  int64
	SCLH_CycleWindowNS    int64
	SCLH_CycleWindowCount int64
	SCLH_LastStepNS       int64
	v_GlobalVars          DB_GlobalVars
}

type DB_GlobalVars struct {
	v_BOUT_A      bool
	v_BOUT_B      bool
	v_BSTART_A    bool
	v_BSTART_B    bool
	v_COUNTER_A   int32
	v_COUNTER_B   int32
	v_FaultReset  bool
	v_FaultStatus bool
	v_Hmibutton   [10]bool
	v_ValveClose  bool
	v_ValveCtrl   DB_FB_ValveControl
	v_ValveOpen   bool
	v_ValveState  int16
}

type DB_FB_ValveControl struct {
	SCLH_InitDone bool
	v_AutoManual  bool
	v_CloseCmd    bool
	v_CLOSECMD_R  bool
	v_CloseLimit  bool
	v_FaultLocked bool
	v_FaultReset  bool
	v_FaultStatus bool
	v_OpenCmd     bool
	v_OPENCMD_R   bool
	v_OpenLimit   bool
	v_OverCurrent bool
	v_ValveClose  bool
	v_ValveOpen   bool
	v_ValveState  int16
}
