// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"fmt"
	"testing"
)

type TestObservationHooks interface {
	OnTestStart(TestStartEvent)
	OnStep(TestStepEvent)
	OnAssert(TestAssertEvent)
	OnTestComplete(TestCompleteEvent)
}

type TestStartEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
}

type TestStepEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	ClockNow   TIME
}

type TestAssertEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	Passed     bool
	Condition  string
	Operator   string
	Got        string
	Expected   string
	Tolerance  string
	ClockNow   TIME
}

type TestCompleteEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Passed     bool
	Steps      int
	ClockNow   TIME
}

type TestRuntimeContext struct {
	Hooks TestObservationHooks
}

func NewTestRuntimeContext(hooks TestObservationHooks) *TestRuntimeContext {
	return &TestRuntimeContext{Hooks: hooks}
}

func observeTestStart(ctx *TestRuntimeContext, event TestStartEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestStart(event)
	}
}

func observeTestStep(ctx *TestRuntimeContext, event TestStepEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnStep(event)
	}
}

func observeTestAssert(ctx *TestRuntimeContext, event TestAssertEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnAssert(event)
	}
}

func observeTestComplete(ctx *TestRuntimeContext, event TestCompleteEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestComplete(event)
	}
}

func testObservationString(value any) string {
	return fmt.Sprint(value)
}

func resetGeneratedTestBuiltinsState() {
}

func resetGeneratedTestRuntimeState() {
	resetGeneratedTestBuiltinsState()

}

func TestUserCase001_Test1(t *testing.T) {
	t.Parallel()
	runTestUserCase001_Test1(t, nil)
}

func runTestUserCase001_Test1(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 28, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 28, Column: 1, Passed: passed, Steps: 4, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 41, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[0] = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 42, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[1] = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 43, Column: 5, Step: 3, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 44, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_FaultStatus
		expectedValue := false
		assertPassed := (mem.v_GlobalVars.v_FaultStatus == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "test1", StableID: "scltest:Test/valve_test.scltest:L28:C1:test1", SourcePath: "Test/valve_test.scltest", Line: 44, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.FaultStatus = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/valve_test.scltest:44:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase002_Test2(t *testing.T) {
	t.Parallel()
	runTestUserCase002_Test2(t, nil)
}

func runTestUserCase002_Test2(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 48, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 48, Column: 1, Passed: passed, Steps: 5, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 61, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[0] = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 62, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[1] = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 63, Column: 5, Step: 3, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[4] = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 64, Column: 5, Step: 4, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(2)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 65, Column: 5, Step: 5, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_ValveOpen
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_ValveOpen == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "test2", StableID: "scltest:Test/valve_test.scltest:L48:C1:test2", SourcePath: "Test/valve_test.scltest", Line: 65, Column: 5, Step: 5, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.ValveOpen = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/valve_test.scltest:65:5 step 5: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase003_Test3(t *testing.T) {
	t.Parallel()
	runTestUserCase003_Test3(t, nil)
}

func runTestUserCase003_Test3(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "test3", StableID: "scltest:Test/valve_test.scltest:L68:C1:test3", SourcePath: "Test/valve_test.scltest", Line: 68, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "test3", StableID: "scltest:Test/valve_test.scltest:L68:C1:test3", SourcePath: "Test/valve_test.scltest", Line: 68, Column: 1, Passed: passed, Steps: 3, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "test3", StableID: "scltest:Test/valve_test.scltest:L68:C1:test3", SourcePath: "Test/valve_test.scltest", Line: 80, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[3] = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test3", StableID: "scltest:Test/valve_test.scltest:L68:C1:test3", SourcePath: "Test/valve_test.scltest", Line: 81, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test3", StableID: "scltest:Test/valve_test.scltest:L68:C1:test3", SourcePath: "Test/valve_test.scltest", Line: 82, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_FaultStatus
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_FaultStatus == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "test3", StableID: "scltest:Test/valve_test.scltest:L68:C1:test3", SourcePath: "Test/valve_test.scltest", Line: 82, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.FaultStatus = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/valve_test.scltest:82:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase004_Test4(t *testing.T) {
	t.Parallel()
	runTestUserCase004_Test4(t, nil)
}

func runTestUserCase004_Test4(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "test4", StableID: "scltest:Test/valve_test.scltest:L119:C1:test4", SourcePath: "Test/valve_test.scltest", Line: 119, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "test4", StableID: "scltest:Test/valve_test.scltest:L119:C1:test4", SourcePath: "Test/valve_test.scltest", Line: 119, Column: 1, Passed: passed, Steps: 3, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "test4", StableID: "scltest:Test/valve_test.scltest:L119:C1:test4", SourcePath: "Test/valve_test.scltest", Line: 125, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[7] = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test4", StableID: "scltest:Test/valve_test.scltest:L119:C1:test4", SourcePath: "Test/valve_test.scltest", Line: 132, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1000)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test4", StableID: "scltest:Test/valve_test.scltest:L119:C1:test4", SourcePath: "Test/valve_test.scltest", Line: 136, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_BOUT_A
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_BOUT_A == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "test4", StableID: "scltest:Test/valve_test.scltest:L119:C1:test4", SourcePath: "Test/valve_test.scltest", Line: 136, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.bOut_A = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/valve_test.scltest:136:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase005_Test5(t *testing.T) {
	t.Parallel()
	runTestUserCase005_Test5(t, nil)
}

func runTestUserCase005_Test5(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	var runner Runner
	clock := &TestClock{}
	runner.Clock = clock
	mem := &runner.Mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	ctx := NewTestRuntimeContext(hooks)
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "test5", StableID: "scltest:Test/valve_test.scltest:L159:C1:test5", SourcePath: "Test/valve_test.scltest", Line: 159, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "test5", StableID: "scltest:Test/valve_test.scltest:L159:C1:test5", SourcePath: "Test/valve_test.scltest", Line: 159, Column: 1, Passed: passed, Steps: 3, ClockNow: clock.Now()})
	runner.testStep = func(r *Runner) { OB_OB1(&r.Mem) }
	observeTestStep(ctx, TestStepEvent{CaseName: "test5", StableID: "scltest:Test/valve_test.scltest:L159:C1:test5", SourcePath: "Test/valve_test.scltest", Line: 166, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.v_GlobalVars.v_Hmibutton[8] = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test5", StableID: "scltest:Test/valve_test.scltest:L159:C1:test5", SourcePath: "Test/valve_test.scltest", Line: 169, Column: 5, Step: 2, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1000)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "test5", StableID: "scltest:Test/valve_test.scltest:L159:C1:test5", SourcePath: "Test/valve_test.scltest", Line: 172, Column: 5, Step: 3, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.v_GlobalVars.v_BOUT_B
		expectedValue := true
		assertPassed := (mem.v_GlobalVars.v_BOUT_B == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "test5", StableID: "scltest:Test/valve_test.scltest:L159:C1:test5", SourcePath: "Test/valve_test.scltest", Line: 172, Column: 5, Step: 3, Kind: "ASSERT", Passed: assertPassed, Condition: "GlobalVars.bOut_B = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at Test/valve_test.scltest:172:5 step 3: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}
